### ISSUE TITLE
60fps youtube videos won't play above 30.

### ISSUE THREAD

**Issue by Benguin** [i-rinat/freshplayerplugin#107]
Regular flash allows youtube to play videos at 60fps, such as this one https://www.youtube.com/watch?v=fPCudSI2U44 but freshplayer seems locked to 30. (The video must be 720 or 1080 to play in 60fps normally, so when testing ensure that you use these resolutions.)

**Comment by i-rinat** [comment]
First I believed decoding of such streams takes too much CPU time so Flash limits framerate, but that turned out to be wrong. Even with hardware-accelerated video decoding implemented, framerate doesn't go higher 40 fps. Surprisingly, both desktop Chrome and Chrome from ChromeOS have the same limit.

Time tracing showed that decoding routines are capable of much higher framerate. There is no significant delay in presentation pipeline either. Just PepperFlash with particular swf (from Youtube) don't want to go higher than 40 fps.

**Comment by i-rinat** [comment]
Test video player on https://i-rinat.github.io/flash-test-cases/VideoPlayer/index.html plays at 60 fps on my machine. So the issue is definitely connected to Youtube player itself.

For some reason I can't get higher that 30 fps with NPAPI Flash too anymore.

**Comment by i-rinat** [comment]
Flash version of player on Youtube doesn't give more than 30 fps on Windows too.

**Comment by i-rinat** [comment]
Combination of Chrome with PepperFlash having limit of 40 fps, and Youtube giving 30 fps streams, makes fixing the bug impossible. So I don't think it's worth to keep the issue open — I can't do anything with it at all.

**Comment by axfelix** [comment]
Thanks for posting this issue at least, just had the problem myself and glad Google pointed me here, otherwise I probably would've tried harder to narrow down the issue. I also can't get pepper flash to want to go over 40fps.
