### ISSUE TITLE
Cannot play drm videos!

### ISSUE THREAD

**Issue by wzhy90** [i-rinat/freshplayerplugin#108]
Test page:http://v.youku.com/v_show/id_XODI0MjgwNzYw.html
Normally it can watch ten minutes. But now it tells me my browser cannot playback the drm videos

**Comment by beew** [comment]
I tried using flash from ChromeOS image but got black screen with only audio for all flash stream (includung non DRMed ones like Youtube) OS is Fedora 21 64 bt. Install fresh-player-plugin from git yesterday (Jan 20 2015)

**Comment by i-rinat** [comment]
@beew, one must enable 3d by adding `enable_3d = 1` line to `~/.config/freshwrapper.conf` to make ChromeOS' PepperFlash render video.

**Comment by beew** [comment]
After setting enable_3d =1 it works for non drmed videos such as Youtube (and the button to minimize work too as oppose to using flash from chrome (https://github.com/i-rinat/freshplayerplugin/issues/127) but protected contents still don't work. Tried this and it is stuck at loading http://helpx.adobe.com/flash-player/kb/protected-video-content-play.html

Fedora 21 64 bit OS.

**Comment by i-rinat** [comment]
@wzhy90, I still can't reproduce it. It fails to play both in freshwrapper and in Chrome. Perhaps, that are regional restrictions. Using proxy servers in China I can get some other error. I see spinning indicator, but the it says something about connection is too slow. (I don't understand Chinese, and used OCR and machine translation, so I'm not sure about what it really says.)

By the way, I've recently fixed #99, which was caused by character encoding name mismatch. I guess GB2312-80 is similar to GB2312, but iconv doesn't know first one. Patch 59e67d3f744b2310bed01853172bb73ca61a6332 adds an alias for that encoding. This one and #99 could be related, but I have no idea how to check it without working reference in Chrome.

Can you try again with recent version?

**Comment by i-rinat** [comment]
@wzhy90, what about recent version? Does that video work?

**Comment by jdinkel** [comment]
I just did a fresh install of Ubuntu-Gnome 15.04 64-bit.  I fully updated it, then added the "ppa:nilarimogard/webupd8" repository and did an install with `sudo aptitude install freshplayerplugin pepperflashplugin-nonfree ubuntu-restricted-extras flashplugin-installer_` (notice the flashplugin-installer is being blocked from installing).

Youtube works fine and I can do a speedtest at speedtest.net... but when I try to play an Amazon Prime Instant Video it does _not_ work.  I get the player controls and a spinning loading animation for a few seconds and then just a black screen and no sound either.  I tried creating the config file mentioned above with the `enable_3d` line but it did not make any difference.

**Comment by i-rinat** [comment]
@jdinkel,
First of all, installing `hal` is pointless for freshwrapper. Some functions from `hal` are used by NPAPI Flash to acquire machine identifier. Freshplayerplugin doesn't use it, as similar functions are provided by either systemd or D-Bus. You definitely already have D-Bus on you machine installed.

What you need to do is to get PepperFlash from ChromeOS. ChromeOS have a custom build of PepperFlash with enabled DRM-related code. Also Chrome from ChromeOS have a special support code enabled (which does what `hal` was used for). I added similar code into freshwrapper, so all you need to do is to get ChromeOS recovery image, extract `libpepflashplayer.so` from it, put it somewhere on your machine, and edit `freshwrapper.conf` to manually specify path to that PepperFlash plugin.

**Comment by wzhy90** [comment]
@i-rinat Sorry, I have known the problem but I don't want to upgrade the libstdc++-4.8 to libstdc++-4.9.
So I cannot test the ChromeOS 's PepperFlash at all.
