### ISSUE TITLE
twitch chat fails

### ISSUE THREAD

**Issue by ahjolinna** [i-rinat/freshplayerplugin#112]
I have problems with twitch chat, it does not load ...I'm using -git version, for now none of the chats I've tried have worked (like twitch.tv/angryjoeshow, twitch.tv/maliveth)...it seems this problem is back, or is it just me?

**Comment by KamiIntelligence** [comment]
I can confirm, just tried to watch a stream on Twitch, and noticed the chat did not function. (I am also running the git version.)

**Comment by i-rinat** [comment]
I've just realized that I checked twitch chat to only show messages, but never tried to post any message myself. Are you talking about sending messages? Or chat doesn't load at all?

**Comment by ahjolinna** [comment]
@i-rinat : it does not load at all, I get : "Sorry, we were unable to connect to chat. Reconnecting..

**Comment by Bevito** [comment]
Hi, 
I can confirm this too.
Twitch chat failed to load with the error message "Sorry, we were unable to connect to chat. Reconnecting.."
Can we help you to debug it ?

**Comment by LoathingKernel** [comment]
```
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
```
I believe that this console output is relevant to the twitch chat not connecting as it repeats 4 times every at reconnect attempt the chat does.

**Comment by i-rinat** [comment]
> evdns returned code 3

`3` means `DNS_ERR_NOTEXIST`. It's highly unlikely actual DNS lookup fails. More likely `ppb_tcp_socket_connect()` is supplied with a wrong address, which can be there due to another error.

To verify, reconfigure with `cmake -DTRACE_ALL=1 ..` and build freshwrapper again. Done so, output from browser will be enormously large, so it's better to collect it to some file (`firefox > log`, for example). What is interesting, is what parameters `ppb_tcp_socket_connect` is called with. `host=` and `port=` are deserving special attention.

Reconfiguring with `cmake -DTRACE_ALL=0 ..` and building again will disable verbose output.

**Comment by ahjolinna** [comment]
@i-rinat I got this: 

ppb_tcp_socket_connect tcp_socket=321, host=telegraph.twitch.tv, port=843, callback={.func=0x7fa7789f65f0, .user_data=0x7fa777cdb860, flags=0}

ppb_tcp_socket_connect tcp_socket=476, host=telegraph.twitch.tv, port=443, callback={.func=0x7fa7789f65f0, .user_data=0x7fa777cdb940, flags=0}

ppb_tcp_socket_connect_with_net_address tcp_socket=514, addr={0x7fa773009c9c}, callback={.func=0x7fa7789f65f0, .user_data=0x7fa7752a6790, .flags=0}

ppb_tcp_socket_connect tcp_socket=767, host=199.9.249.252, port=843, callback={.func=0x7fa7789f65f0, .user_data=0x7fa7752a6b90, flags=0}

ppb_tcp_socket_connect tcp_socket=782, host=199.9.249.252, port=443, callback={.func=0x7fa7789f65f0, .user_data=0x7fa7752a6b80, flags=0}

ppb_tcp_socket_connect tcp_socket=1525, host=199.9.249.222, port=843, callback={.func=0x7fa7789f65f0, .user_data=0x7fa7752a6de0, flags=0}

ppb_tcp_socket_connect tcp_socket=1541, host=199.9.249.222, port=443, callback={.func=0x7fa7789f65f0, .user_data=0x7fa7752a6de0, flags=0}

...there is way more
the whole log file is here: https://app.younited.com/?shareObject=a33dfe4a-b790-a6df-1e57-01e1883183f3

**Comment by ahjolinna** [comment]
@i-rinat : why no fix yet?

**Comment by i-rinat** [comment]
@ahjolinna, there is no fix for the issue yet because:
(a) I can't reproduce it, chat loads fine on my machine, so I can't even guess what goes wrong on your setup. Log file doesn't help too much — there are records about established connections, but there are also records about failed for unknown reason ones (199.9.250.239:80 is available here, for example);
(b) I'm doing this project on my free time. I'm trying to make it work well, but I'm not a wizard.

If you have an idea what's wrong with the particular piece of code and/or have an idea how to fix it, please let me know. If you have a patch, which solves some issue and doesn't break anything else, please share it, I'll merge it. (After style cleanup, perhaps.)

**Comment by ahjolinna** [comment]
@i-rinat : I just installed freshplayerplugin-git on my ultrabook and it seems that twitch chat works on it

**Comment by Bevito** [comment]
I'm not sure that I can help, but I uploaded my log file here : http://dl.free.fr/kmSHOSALc
Thanks for your help and your support.

**Comment by i-rinat** [comment]
@ahjolinna, do you have any packet filtering enabled on your desktop machine?

**Comment by i-rinat** [comment]
@Bevito, @ahjolinna, please try 317eda1a0f2b31be43624cf0fecfc35fdcdc99eb. In the logs from both of you all failed DNS resolutions was already IP addresses. So I've added another code branch to detect whenever passed host name is in appropriate format.

**Comment by ahjolinna** [comment]
@i-rinat : now it works ...thanks

**Comment by Bevito** [comment]
Great, now it works.
Thanks a lot !

**Comment by i-rinat** [comment]
So, that was the reason...
But do /etc/resolv.conf really differ on your laptop and desktop, @ahjolinna ?

**Comment by ahjolinna** [comment]
Desktop:
search elisa-laajakaista.fi
nameserver 195.197.54.100
nameserver 193.229.0.40
Laptop:
nameserver 192.168.43.1

**Comment by i-rinat** [comment]
I see. Laptops talks to a local caching DNS server (dnsmasq, perhaps), which handles IP addresses as well. I've tried now to switch to Google's DNS (8.8.8.8), and have reproduced bug too.
