### ISSUE TITLE
I continue with tearing :(

### ISSUE THREAD

**Issue by pandev92** [i-rinat/freshplayerplugin#131]
I tried anything but in my gnome shell, I have tearing when I use freshplayer plugin, I tried "exp_enable_3d = 1
" but this don't affect to my system.

**Comment by i-rinat** [comment]
Yep, there were no changes related to tearing both recently and at whole project duration time. I digged into the issue, but it seems tearing is a very hard problem which have no well-known solution. I plan to experiment with some DRI2-related technique, and post update here after that. But I don't know when it would be.

As for "`exp_enable_3d`", this option doesn't exist anymore, it was renamed to "`enable_3d`". Rename reason was enabling it by default, but since then I disabled it again. So the only visible change is naming/

**Comment by i-rinat** [comment]
(related: #96, #74)

**Comment by ahjolinna** [comment]
I had little bit flickering with "enable_3d = 1", or then it's really bad tearing :D
I'm using nvidia gpu (gtx560ti) with latest non-free drivers

**Comment by i-rinat** [comment]
You can try `compton`, various backends and vsync methods.

On my machine `compton --backend glx` works great, till some fullscreen OpenGL application launchs, which freezes graphics completely. Although `compton --backend xrender --vsync opengl` seems to be working fine.

**Comment by i-rinat** [comment]
There's no way to fight tearing inside application. As plugin model assumes all instances do drawing in one thread one after another, waiting for vsync makes no sense. There would be enormous lags.
