### ISSUE TITLE
use Jack or PulseAudio?

### ISSUE THREAD

**Issue by wzhy90** [i-rinat/freshplayerplugin#163]
Which is better for performance?
My laptop is i3-350 and 8G ram

**Comment by i-rinat** [comment]
I think PulseAudio will consume a bit less CPU than JACK at the price of higher latency. Having a larger target latency, PA wakes up CPU less often, and doesn't imply mandatory format conversion (interleaved 16-bit stereo → separated 32-bit float channels → soundcard format, which is probably 16-bit too).

So I'd personally prefer PA in that case, it's enough for me, as I don't need guarantees that JACK provide.

JACK output code is new, and occasional click due to buffer underruns still occur. I don't know how to fix it yet. Perhaps only my current setup suffers from underrun — I didn't changed settings to allow realtime priority.
