### ISSUE TITLE
How to make it do not black the screen light when playing video?

### ISSUE THREAD

**Issue by wzhy90** [i-rinat/freshplayerplugin#164]
As the title

**Comment by i-rinat** [comment]
Freshwrapper supports XScreenSaver and freedesktop.org compatible screensavers, but doesn't have DPMS support. Do you have DPMS enabled? (What is output of `xset q` command?)

**Comment by wzhy90** [comment]
```
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00000000
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    off    02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     off    13: Mouse Keys:  off
  auto repeat delay:  500    repeat rate:  33
  auto repeating keys:  00ffffffdffffbbf
                        fadfffefffedffff
                        9fffffffffffffff
                        fff7ffffffffffff
  bell percent:  50    bell pitch:  400    bell duration:  100
Pointer Control:
  acceleration:  1/1    threshold:  4
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  0    cycle:  0
Colors:
  default colormap:  0x22    BlackPixel:  0x0    WhitePixel:  0xffffff
Font Path:
  /usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins
DPMS (Energy Star):
  Standby: 0    Suspend: 0    Off: 0
  DPMS is Enabled
  Monitor is On
```

**Comment by i-rinat** [comment]
From `xset q` output I can say, DPMS timers are not enabled.

If I recall correctly, you are using Mint 17 (or 17.1). Its cinnamon-screensaver doesn't fully implement fd.o screensaver dbus interface, `SimulateUserActivity` call have no effect there.
Fortunately, it's easy enough to use Cinnamon-specific interface, which is implemented in 891bce3b8c60bcc9aed54aab775c717a421ce906.

Is it working now?

**Comment by bootkiller** [comment]
Screensaver also isn't prevented here. Using Plasma 5:

```
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00000002
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    on     02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     off    13: Mouse Keys:  off
  auto repeat delay:  660    repeat rate:  25
  auto repeating keys:  00ffffffdffffbbf
                        fadfffefffedffff
                        9fffffffffffffff
                        fff7ffffffffffff
  bell percent:  50    bell pitch:  400    bell duration:  100
Pointer Control:
  acceleration:  1/10    threshold:  4
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  0    cycle:  600
Colors:
  default colormap:  0x20    BlackPixel:  0x0    WhitePixel:  0xffffff
Font Path:
  /usr/share/fonts/misc/,/usr/share/fonts/TTF/,/usr/share/fonts/Type1/,/usr/share/fonts/100dpi/,/usr/share/fonts/75dpi/,built-ins,/home/boot/.fonts
DPMS (Energy Star):
  Standby: 600    Suspend: 900    Off: 1200
  DPMS is Enabled
  Monitor is On

```

**Comment by i-rinat** [comment]
@bootkiller, try with current version again. In e6a2dd0485b0136739614bf94d4ebd0b4ff0e7d4 I've added internal X screen saver timer resetting, it should prevent monitor from switching off.

To simplify testing, DPMS timeouts can be changed by calling `xset dpms 30 60 90`. That command will make monitor to go to standby mode after 30 seconds of inactivity, to suspend mode after 60 seconds, and turn off after 90 seconds. Setting value to 0 disables corresponding timer.

**Comment by bootkiller** [comment]
@i-rinat It's working now, but only if the video is in fullscreen mode. If not in fullscreen, it still enters power saving mode.

**Comment by i-rinat** [comment]
@bootkiller, try code from [tmp-log-update-activity](https://github.com/i-rinat/freshplayerplugin/tree/tmp-log-update-activity) branch. Launch browser from terminal and try to notice, whenever lines "ppb_flash_update_activity called" printed to stdout, for regular and fullscreen modes. I think they should appear once per circa 10 seconds.

**Comment by bootkiller** [comment]
@i-rinat Messages are printed on both modes.

**Comment by i-rinat** [comment]
Flash calls that method on a regular basis. And I forward those calls to XScreenSaver and dbus-based interfaces of other screen savers. I asked you to try instrumented code to find out whenever Flash still calls that method. It calls, it seems.

Meanwhile I tried to install Plasma 5 in Arch VM, and (org.freedesktop.ScreenSaver, /org/freedesktop/ScreenSaver, org.freedesktop.ScreenSaver.SimulateUserActivity) method doesn't work. I also tried org.kde.screensaver interface and all related paths, they all aren't working.

However I found that there is workaround: to call both SimulateUserActivity() and GetSessionIdleTime().

**Comment by i-rinat** [comment]
If you want to test dbus interface, here is a script that should prevent screen saver from launching:

```bash
while true; do qdbus org.freedesktop.ScreenSaver /org/freedesktop/ScreenSaver org.freedesktop.ScreenSaver.SimulateUserActivity; date; sleep 10; done
```

**Comment by i-rinat** [comment]
@bootkiller, I've added workaround for Plasma 5 screen locker in 540cb83aeef4b4d189850918c02fc94bcf4c2575.
Line `quirk_plasma5_screensaver = 1` needs to be added to `~/.config/freshwrapper.conf` in order to enable workaround code.

**Comment by wzhy90** [comment]
fixes in my laptop

**Comment by bootkiller** [comment]
@i-rinat, everything is working now, thanks.

**Comment by i-rinat** [comment]
OK, great.

**Comment by mgraesslin** [comment]
Plasma's screen locker maintainer speaking here: please use Inhibit instead of SimulateUserActivity.

**Comment by i-rinat** [comment]
> please use Inhibit instead of SimulateUserActivity.

Are there any reasons to prefer one over another?

Main obstacle on using `Inhibit` method is to understand when to call `UnInhibit`. PPAPI doesn't have equivalent of those methods. Instead it has a method `PPB_Flash_13_0.UpdateActivity` which should be called from time to time to inhibit screen saver, just like `SimulateUserActivity`. Converting to Inhibit/UnInhibit will require additional care, some magic timeout to detect whenever calls of `PPB_Flash_13_0.UpdateActivity` stopped or not.

**Comment by mgraesslin** [comment]
Inhibit tells the screen locker infrastructure that an application wants to inhibit the lock screen. Ideally that also allows to show in the UI that the screen is inhibited and why. This is the way how it is meant to be used. With SimulateUserActivity you need to constantly call it, keeping both your application as well as the lock screen application busy with handling that. You don't know the idle interval used by the lock screen, so you need to use a small interval. And as you noticed, this is not how it's supposed to be used and it broke. Nobody tests whether the SimulateUserActivity works and it's only provided for legacy reasons.

Overall: if you are able to go to inhibit, please do so. You win a better integration in all desktops and you can in addition also inhibit the power management, so that the system doesn't suspend while the application is playing.

**Comment by i-rinat** [comment]
At the moment all I have is periodical calls from PepperFlash. There are no explicit "start inhibiting" and "stop inhibiting" calls in PPAPI, there is only `SimulateUserActivity` equivalent. Deducing stop time from periodic calls would be an error-prone procedure (as one must to either start a thread that does estimations, of throw another bunch of asynchronous tasks into event loop). I think it's better to rely on screen saver itself.

Why can't be `SimulateUserActivity` fixed in Plasma 5 screen locker itself? Doesn't look like it's not implemented there at all.

**Comment by i-rinat** [comment]
Also doesn't https://github.com/i-rinat/freshplayerplugin/issues/164#issuecomment-93294103 help to make it working?

**Comment by mgraesslin** [comment]
> There are no explicit "start inhibiting" and "stop inhibiting" calls in PPAPI, there is only SimulateUserActivity equivalent

That's bad. I can promise you that this won't work on Wayland. E.g. the system might go to suspend, because it's not inhibited and on Wayland SimulateUserActivity will only affect the lock screen and not any other applications.

> Why can't be SimulateUserActivity fixed in Plasma 5 screen locker itself? Doesn't look like it's not implemented there at all.

It is implemented, see: https://quickgit.kde.org/?p=kscreenlocker.git&a=blob&h=dc216fb06ccb63e3a3fbce138bd052a93c2495bc&hb=687272c11e4d51ea014779eb6b7e767ef11f0996&f=interface.cpp line 157.

KIdleTime is windowing system specific and depends on what the windowing system provides. It's quite possible that the used implementation just cannot provide it.

I couldn't find what the SimulateUserActivity should do, but what I found were discussions about removing it from the DBus interface. Please consider it as deprecated and not supported by all DEs (I'm not sure whether GNOME has support for it).

I can only recommend you to go for inhibit.

**Comment by i-rinat** [comment]
> I can promise you that this won't work on Wayland.

This whole NPAPI thing is tied to X server with rusty nails :smile:, so I'd not worry about Wayland incompatibility.

> will only affect the lock screen

From interface name `org.freedesktop.ScreenSaver` I'd expect it to control screen saver (only), so that's fine.

> It is implemented

Then why did you ever noticed this issue? Back when I tested Plasma 5 screen locker, it had a strange behavior. It ignored `SimulateUserActivity` calls when they were by themselves. But if one calls `GetSessionIdleTime` after `SimulateUserActivity`, latter began to work as expected. There is code that does so in freshwrapper. One needs to add `quirk_plasma5_screensaver = 1` line to configuration file to enable that code.

> I couldn't find what the SimulateUserActivity should do, but what I found were discussions about removing it from the DBus interface.

Could you please provide a link to such discussions (or maybe links)? I'd like to read them too.

> I can only recommend you to go for inhibit.
> It's quite possible that the used implementation just cannot provide it.

This is still looks weird for me. Assuming I have nothing other than periodic calls, each denoting screen saver shouldn't fire up, how I'm expected to convert it to Inhibit/UnInhibit calls if implementation cannot do the same? Either implementation can't do it because it's not possible, and then I can't do it too for the same reason. Or implementation can do it, and I can too.

I never wrote a screen saver, but here is how I would do it. There would be some counter, which is initialized to `0`. Also there would be a thread which runs infinite cycle with small workload of incrementing the counter and subsequent `sleep(1);`. When counter reaches certain value (say, `15*60` for 15 minutes timeout), screen locks. Every user activity resets the counter to its initial value (0). Every call to `SimulateUserActivity` resets counter to its initial value (0). Call to `Inhibit` sets increment to 0. Call to `UnInhibit` sets increment to 1. (It's also worth to handle cases where multiple clients call Inhibit/UnInhibit with proper "depth" checking).

See? Both ways of temporary screen saver disable, fit straightforward implementation just fine. It's also easy to go from one to another if you, say, implement a standalone video player. You know when video starts, you know when it pauses, you know when it stops. Freshwrapper knows nothing. There is no reliable way to discern a video from some background animation. They're all just `swf`.

**Comment by i-rinat** [comment]
> I'm not sure whether GNOME has support for it

All gnome-screensaver, cinnamon-screensaver, mate-screensaver, kde-screensaver (KDE4), Plasma 5 screenlocker have that method. Either on some specific interface, or at `org.freedesktop.ScreenSaver`. XScreenSaver have no D-Bus interface, but it also have a way to postpone activation.

From list above, the only difference is Plasma 5. But `SimulateUserActivity` also works there, if followed by `GetSessionIdleTime`.

**Comment by mgraesslin** [comment]
> This whole NPAPI thing is tied to X server with rusty nails :smile:, so I'd not worry about Wayland incompatibility.

It matters as soon as the lock screen is Wayland powered. What the client speaks is irrelevant.

> Then why did you ever noticed this issue?

I don't use your application, sorry :-) I was just pointed here and thought I provide some feedback to help you integrate better.

> Could you please provide a link to such discussions (or maybe links)?
the thread: http://lists.freedesktop.org/pipermail/xdg/2012-November/012576.html

> how I'm expected to convert it to Inhibit/UnInhibit calls if implementation cannot do the same?

I don't know the API you are using. But I honestly cannot believe that there is nothing you could use for turning it into Inhibit/Uninhibit. Why do I think that SimulateUserActivity should not do it: because it misses context for the lock screen. It is a way to allow malicious applications from stopping the lock screen from showing up ever. On the other hand with inhibition we have more information we can provide and even give the user a choice to ignore inhibtion. That's just not possible with SimulateUserActivity.

> Also there would be a thread which runs infinite cycle with small workload of incrementing the counter and subsequent sleep(1);

erm no :-) Of course a lock screen is not using an infinite cycle, but rather sleeps till it gets the idle event. This is one of the things I don't like about your SimulateUserActivity approach: it wakes up the screen locker. It should not do anything till it needs to do something.

**Comment by i-rinat** [comment]
> I don't use your application, sorry :-)

Oh. I did a wrong assumption.

> But I honestly cannot believe that there is nothing you could use for turning it into Inhibit/Uninhibit.

Of course it's possible. But I don't see why there is a need to reinvent the wheel, when all screen savers already have that.

> Why do I think that SimulateUserActivity should not do it: because it misses context for the lock screen. It is a way to allow malicious applications from stopping the lock screen from showing up ever.

Doesn't look like a reasonable protection unless there is an external authority which can confirm application name. Malicious app could send various randomly-generated names, or send names of well-known applications.

> This is one of the things I don't like about your SimulateUserActivity approach: it wakes up the screen locker. It should not do anything till it needs to do something.

So it creates an timeout and waits, that's great. But won't it be woken by real user activity: key presses, mouse movements? Why D-Bus call makes it worse?

**Comment by mgraesslin** [comment]
> Malicious app could send various randomly-generated names, or send names of well-known applications.

That's true. But we can expose it in the user interface and if there is a "VLC", which is not running at all, the user will notice. Also KDBus will provide us more information about the peer.

At the moment this is all theoretical. As you point out there is no real security. This will change, I'm working on protecting the lock screen against internal attacks on Wayland. With Wayland we will not be able to provide SimulateUserActivity.

> So it creates an timeout and waits, that's great. But won't it be woken by real user activity: key presses, mouse movements?

No of course not, that would be rather stupid. The lock screen doesn't get woken up, unless the idle time is reached to activate.

> Why D-Bus call makes it worse?

Because it wakes up the idle application.

**Comment by i-rinat** [comment]
> I was just pointed here and thought I provide some feedback to help you integrate better.

Thanks for information.
Although I'm not going to change approach at the moment, it could change in the near future. And information you provided helps to understand situation better.

**Comment by i-rinat** [comment]
> Also KDBus will provide us more information about the peer.

With information about peer available, explicit name statement loses all security-related benefit. Why to bother with parameters if you can just test who the sender is?

> No of course not, that would be rather stupid. The lock screen doesn't get woken up, unless the idle time is reached to activate.

What wakes lock screen then? Doesn't it monitor user activity?


> Because it wakes up the idle application.

I'm confused. Am I right that screen locker handles D-Bus calls, but user activity monitored by some other application?

**Comment by mgraesslin** [comment]
> Doesn't it monitor user activity?

It's using XSyncAlarm, see http://www.x.org/releases/X11R7.7/doc/xextproto/sync.html - which means it gets an event from the windowing system once the idle time is reached.

> Am I right that screen locker handles D-Bus calls, but user activity monitored by some other application?

yes, user activity is monitored by Xserver.

**Comment by i-rinat** [comment]
> xextproto/sync

Oh... I was unaware of its existence. Thanks!

I wonder what else X server have...
