### ISSUE TITLE
[Proposal] Widevine CDM

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [i-rinat/freshplayerplugin#167]
It would be nice if this plugin could be eventually made to conveniently support the Widevine CDM from Google Chrome, so that Netflix could be watched on Linux in open-source browsers such as Firefox and Pale Moon (*à la Pipelight*), but without the overhead of Wine.

**Comment by i-rinat** [comment]
Is there any test page for Widevine CDM?

I tried https://www.widevine.com/demo/index.html and http://flowplayer.electroteque.org/widevine, but with no success. They're trying to load plugin for MIME type `application/x-widevinemediaoptimizer` while Widevine module in Chrome uses type `application/x-ppapi-widevine-cdm`. What I need is something that works in Chrome (or Chromium). Netflix itself is not available in Russia, so I can't use it for testing.

**Comment by JamesTheAwesomeDude** [comment]
@i-rinat I don't know if any sites other than Netflix use Widevine CDM.

I just realized that the interface Netflix/Widevine uses [seems to be EME](http://en.wikipedia.org/wiki/Netflix#Linux_support) instead of NPAPI, so this proposal may actually be outside of even the future realm of this project.

**Comment by i-rinat** [comment]
I've pushed code for Widevine CDM wrapper to [widevine](https://github.com/i-rinat/freshplayerplugin/tree/widevine) branch. There is no new interfaces implementations, just boilerplate code. I don't know what should it do, currently it does nothing.
Reconfigure with `cmake -DWITH_WIDEVINE=1 ..` to enable wrapper creation.

**Comment by i-rinat** [comment]
From superficial analysis, I can conclude, Widevine CDM is not used as browser plugin in a traditional sense, but rather as backend for Encrypted Media Extensions (EME). So to use it in Firefox, it should be called from JS core, but NPAPI is not designed for that.

So it's not possible to implement such support at the moment.

**Comment by i-rinat** [comment]
I've did a research on content decryptor modules in Firefox. Mozilla have added another plugin infrastructure, Gecko Media Plugins recently to support CDM (and HTML5 Encrypted Media Extensions, EME). Those are initially sandboxed plugins, which can be used to encode and decode video (openh264) and do content decryption (Adobe Prime, I guess).

Connecting Widevine should be performed through that interface, rather than NPAPI. And since Chrome have CDM and its PPAPI adapter separated, it could be done without ever touching PPAPI interface at all, I think.

I tried to experiment with GMP plugins, but found out, that even clearkey [1] CDM didn't work. Looks like essential Javascript APIs are not yet landed in Firefox. Perhaps there are enough to get Adobe Prime working on Windows on selected sites, but it's not complete. Some of functions were added to development version of Firefox only about two or three weeks ago, so maybe it's not that far away.

So even if anybody decides to adapt Widevine CDM to Firefox, it's too early.

[1] Clearkey is an example decryptor module with decryption algorithm known and described, and key passed as clear text, hence the name. Every implementation of HTML5 EME should have it.

**Comment by nerijus** [comment]
chrome://plugins/ displays Widevine Content Decryption Module as Type: PPAPI. Does it mean it uses PPAPI interface?

**Comment by i-rinat** [comment]
> Does it mean it uses PPAPI interface?

Yep, it uses `PPB_ContentDecryptor_Private` and `PPP_ContentDecryptor_Private` interfaces with some other helpers. More specifically, it's the `libwidevinecdmadapter.so` which uses them. It acts as a bridge between Chrome and actual CDM, `libwidevinecdm.so`. CDM itself uses different API.

**Comment by nerijus** [comment]
Just FYI, https://github.com/i-rinat/gmp-widevine works with FF 45 beta.
