### ISSUE TITLE
Mouse wheel scroll amount

### ISSUE THREAD

**Issue by i-rinat** [i-rinat/freshplayerplugin#170]
It was reported in https://github.com/i-rinat/freshplayerplugin/issues/72#issuecomment-96267978 that in Firefox and freshwrapper mouse wheel scrolls (smth.) about twice as more as in Chrome. At least in thesettlersonline.ru.

**Comment by i-rinat** [comment]
@Ri0n, there was twice as many scrolling events generated. Fixed in 78caa2dbac15bf8b02686d1d8130ba7a4fe739cc. Note in PepperFlash (in Chrome) on tick moves list by three lines, while in Flash 11.2 (in Firefox) only by one line.

Scrolling of a list can be tested on [this page](http://i-rinat.github.io/flash-test-cases/ListWidget/).

**Comment by Ri0n** [comment]
thanks.

btw is it know problem freshplayer often fails on http requests? especially under load

**Comment by i-rinat** [comment]
> is it know problem freshplayer often fails on http requests?

I didn't know about that. What exactly do you mean by "fails"? Is it unable to load URL or whole plugin crashes? If it crashes, does it crash instantly or does it freeze for about half a minute and crashes after that?

**Comment by Ri0n** [comment]
Ok that was just an assumption.

This all about my favorite game thesettlersonline.ru =)
On start it sends hundreds of http requests and sometimes it just stops in the middle of loading process. I guess it's because it does not receive reply to some critical request.
Sometimes I also see the game can't load some textures.

Opening firebug in Firefox usually helps with loading. I guess it's because firebug slows down network requests intercepting all traffic.

I have ~60Mbit Internet connection.

**Comment by Ri0n** [comment]
and yes, it does not resume.
