### ISSUE TITLE
Is Intel Graphic need to install libvdpau-va-gl to enable 3d support?

### ISSUE THREAD

**Issue by wzhy90** [i-rinat/freshplayerplugin#171]
As the title. Because the NPAPI Flash Plugin only use vdpau to support the 3D and hw encode

**Comment by i-rinat** [comment]
Short answer is "no".

PepperFlash as opposed to NPAPI Flash is designed to run in a sandbox, where all communication with outer world is performed through PPAPI. That means PepperFlash won't even try to directly open files in a filesystem, or access hardware acceleration APIs like VDPAU. Chrome sandbox simply won't allow that. This is why PPAPI is so huge — it comprises almost everything plugin would need.

There are interfaces for 2d and 3d ([OpenGL|ES2](https://www.khronos.org/opengles/)) graphics, which are implemented. And there are interfaces for hardware video decoding, which are currently not.

So since VDPAU is not involved, you don't need libvdpau-va-gl.

Before I started, I can't say for sure which hw decode interface I'll choose. If for some reason it will be VDPAU, then libvdpau-va-gl would help.
