### ISSUE TITLE
v4l is mandatory - Can this be made optional?

### ISSUE THREAD

**Issue by chaoskagami** [i-rinat/freshplayerplugin#209]
I have a LFS system. I'm forced to install v4l libraries - my kernel has no support for this compiled in, and I don't even have a webcam to use v4l with. Can this be made optional somehow, or at very least stubbed out?

**Comment by i-rinat** [comment]
I've just tried to make libv4l2 dependency optional and to not compile `ppb_video_capture.c`. Although it can be built without issues, when running, PepperFlash refuses to operate:
```
[ERROR:flash/platform/pepper/pep_module.cpp(143)] Browser does not support interface PPB_VideoCapture(Dev);0.3.
```
To make that work, I'll need to invade source file with preprocessor directives to cut everything that ever makes use of libv4l2. I'd like to avoid that, because it makes the whole project worse. After all, libv4l2 takes only two minutes to compile.

**Comment by i-rinat** [comment]
By the way, do your system have `/usr/include/linux/videodev2.h` ?

**Comment by chaoskagami** [comment]
I do have that kernel header. My kernel is obviously missing the modules for v4l, though, so there's no webcams to find.

For now, I did install libv4l2 just to get this working, since linux npapi flash is beyond insecure. Since libv4l2 is mostly a wrapper around the kernel interface with format conversion code, is it possible to just use the kernel headers directly?

Still, I think installing a whole library for it to be not even used is kind of a bug.

**Comment by i-rinat** [comment]
Implemented in 4e127a49b15fd75b839c1c79aef168c4d7b0d775. Configure with `cmake -DWITH_LIBV4L2=0 ..` to avoid using of libv4l2.

**Comment by i-rinat** [comment]
> My kernel is obviously missing the modules for v4l, though, so there's no webcams to find.

Presence of cameras doesn't matter. What really matters is presence of that header file, because its absence will fail compilation. With no cameras in the system, no cameras will be detected at run time. That's fine.

> Since libv4l2 is mostly a wrapper around the kernel interface with format conversion code, is it possible to just use the kernel headers directly?

Yep, it's possible. One needs to add code working in mmap, read/write, and streaming modes with proper detections of capabilities. Also all supported by V4L2 formats should have corresponding format conversion code. Also, with proper detection. One needs to test it on wide variety of hardware to track bugs.

Or, just use libv4l2, because it does all that, and well tested because widely used.

You can also create drop-in replacement of libv4l2 with more permissive license, so I can just put its sources into the project, compile it and statically link to it.

> Still, I think installing a whole library for it to be not even used is kind of a bug.

No, it's not a bug. At most it's a missing feature.

I still don't get why are you so concerned about that library. Freshwrapper uses more than a dozen of others. Most of them are bigger and heavier than libv4l2.

**Comment by chaoskagami** [comment]
I'm not really all that concerned...it's much the same kind of issue as having needed OpenGL ES support in mesa at a point a month or so ago.

If I don't need a feature, it's wasting precious megabytes of hard disk space with code which will just be disabled with a config file or implicitly from lack of support anyways.

Most of the others are base requirements for an operational desktop system, so they don't bother me really. Other software would have dragged all of those in eventually, and in fact had been dragged in before I even built freshwrapper.

Since this is fixed, I'll just close it now.
