### ISSUE TITLE
Support for Android :) 

### ISSUE THREAD

**Issue by LifeIsStrange** [i-rinat/freshplayerplugin#210]
It will be wonderful if Firefox for Android was supported by fresh player ! 
Why ? Because flash is dead on Android and shumway is not ready :/
It will be a revolution and Firefox will be more famous and use with the exclusivity of flash player 17, and YOU devloppers will earns probaly very more donations ! 
I am very sorry for my very bad english, and thanks for your amazing work, you are modern heroes, the developpers of the magic World of the free software !

**Comment by i-rinat** [comment]
I thought about Android before, and have to say, it's too hard.

It's not like throwing in another thousand lines of code. Almost everything should be rewritten, as almost everything in the project is platform-dependent code. It would be so big, that easier to make another project targeting Android, rather than extend this one.

**Comment by LifeIsStrange** [comment]
(again sorry for my bad english) 
But Android is Linux based and share many libs  :( but you have probably reason, you are far more qualified than me ^^. 
Unfortunately I do not know code.
There fortunately the incoming shumway ! 
Thank you for your rapid answer and thanks à lot for your fresh player plugin ! I love this soft ! 
Good Luck !

**Comment by LifeIsStrange** [comment]
Also, I am new on github, I don't know how the system issue work ^^, I must close the issue ? Or leave open ?

**Comment by LifeIsStrange** [comment]
Also again (sorry..)  if your really want à port for Android but if you have not the time, you can maybe ask help at the mozilla shumway team to port you soft on Android ? Because you have the same finality, bring flash player on all the platforms  :)  I can maybe find developpers for you ! will be a great contribution to humanity
You can also make à crowdfunding campain for the port ? (on indiegogo or kickstater) 
I think that it will be very mediatized !! 
I will pay you and help you but i can't because i am Just à teenager with no money.. 
Next year I shall be coded, so I will help you maybe. Sorry for my insistance, it's Just that I think that à port of modern flash for Android will be a great and needed contribution to humanity Who actually can't stream movies or anime or hentais on her smartphone :'(
Yes, I am utopic haha

**Comment by SirOfTheRepo** [comment]
Mozilla's official statement on the matter is that plugin based web is going to die sooner or later.
They do not support such efforts, and I've got to agree to them in doing so.

We've got to accept Flash is dead (or it is going to be in a future that I hope not too far), and while this is an awesome effort by i-rinat to let us view Flash on Firefox on Linux, it is not simply worth the effort of doing much more.

Just accept it has no reason to happen, and the only way you've got to contribute (you need no money for it) is by avoiding flash content altogether to let it die sooner.

There is no such thing as "modern flash", its an old and seriously flawed technology, and there are replacements for it.
Express to the websites you use who have flash that you can't view them, and that modern HTML5 players would solve it. They know it, but need pressure to have the effort to do so.

**Comment by i-rinat** [comment]
> But Android is Linux based and share many libs

Actually, no. There is a reason because Linux is sometimes called GNU/Linux. It's Linux kernel and GNU(-based) user-space programs. In the same way Android should be called Android/Linux, as it uses Linux kernel and Android user-space programs. It have own libc implementation (Bionic), which is not fully-compatible with glibc, busybox-like utilites, named "toolbox", which is also different project.

There are no X server, but rather SurfaceFlinger; AudioFlinger for audio, own interfaces for hardware decoders, and so on. It's completely different for low-level software.

> Unfortunately I do not know code.

You can track how I learned to code in this and other repositories. :-)
If you want to do something, you just start doing it.

> I must close the issue?

As you wish.

> You can also make à crowdfunding campain for the port?

It's not just about money. I personally don't use Android so much. Especially don't use any Flash-based content there. Therefore it won't receive as much testing as I can provide while using it on desktop Linux-machine. That was one of the primary reason I dropped idea of supporting Windows and Mac OS X.

**Comment by LifeIsStrange** [comment]
Sorry I don't know how reuse your commentarys (very bad english..) so i will use " instead. 

" Just accept it has no reason to happen, and the only way you've got to contribute (you need no money for it) is by avoiding flash content altogether to let it die sooner." 
Yes I understund ! I think that I will use popcorntime instead of crap/spy/adware sites of streaming. 

"There is no such thing as "modern flash", its an old and seriously flawed technology, and there are replacements for it."
I didn't knew that, thanks you ! 


"There are no X server, but rather SurfaceFlinger; AudioFlinger for audio, own interfaces for hardware decoders, and so on. It's completely different for low-level software."
Thanks Google..... 

"You can track how I learned to code in this and other repositories. :-)
If you want to do something, you just start doing it." 
Haha thank you ! I go try to understund your code, but in long terme I think that I will learn the Rust programming langage for help the mozillians to build servo :D 

"Therefore it won't receive as much testing as I can provide while using it on desktop Linux-machine. That was one of the primary reason I dropped idea of supporting Windows and Mac OS X." 
If one Day you have for project to port your awesome software to Android, I will can build for you a community of bugs reporters  :) 
But if you never do a port, it's absolutely not important because flash is dead :) 

Thanks for all ❤
PS: sorry for the late of my answer.
