### ISSUE TITLE
When in Fullscreen Fresh Player screen tears on Ubuntu 14.04.2  with Compiz and Unredirect Fullscreen Windows Enabled.

### ISSUE THREAD

**Issue by TheIntelligentMan** [i-rinat/freshplayerplugin#226]
I have this strange issue of screen tearing with the Nvidia driver on Compiz with your plugin.I don't know what's causing this as HTML5 videos don't tear even with Unredirect Fullscreen windows enabled.

**Comment by TheIntelligentMan** [comment]
I'm using firefox if that makes any difference.

**Comment by 3v1n0** [comment]
Mh, it's weird... Since your CCSM -> Composite -> Undirect-Match should contain something such as:
```
(any) & !(class=Totem) & !(class=MPlayer) & !(class=Vlc) & !(class=Plugin-container) & !(class=Firefox) & !(class=QtQmlViewer)
```

And this plugin creates a window with `WM_CLASS(STRING) = "plugin-container", "Plugin-container"`

**Comment by TheIntelligentMan** [comment]
Indeed it's a weird issue.I really don't know what's causing this.

**Comment by i-rinat** [comment]
That's not something unexpected as code was written without considering tearing issues in mind. I do use one-command-copy, with `XRenderComposite` drawing whole frame at a time. But timing can be arbitrary, which can cause tearing if no composite managers are used.

**Comment by TheIntelligentMan** [comment]
So i-rinat can you fix it? The tearing is very annoying for me as I use your plugin for all the video sites.

**Comment by i-rinat** [comment]
I'm thinking on it. Perhaps caching GraphicsExpose events to delay painting till vsync will help.

**Comment by cyberalex4life** [comment]
If you have Intel CPU, it might actually be from the driver. I have this problem on Ubuntu, OpenSuse 13.2, and Manjaro Gnome Shell 13.2. I have an  Intel i7-3610QM Ivy Bridge processor, but I found an workaround on the internet: something like here https://sn0v.wordpress.com/2013/12/17/solve-video-tearing-on-intel-ubuntu-xfce-4/
What I did is:
$ sudo mkdir -p /etc/X11/xorg.conf.d/
because this folder is not created by default (this usually happens to me)
$ sudo gedit /etc/X11/xorg.conf.d/20-intel.conf
then paste this in:
Section "Device"
    Identifier  "Intel Graphics"
    Driver      "intel"
#    Option      "AccelMethod"    	"UXA"
#   Option      "Backlight"       	"acpi_video0"
    BusID       "PCI:0:2:0"
	Option      "TearFree"        	"true" 
EndSection

The '#' lines are commented out (they don't have effect: but fill free to try changing those settings | I tried) The important thing is 'Option      "TearFree"        	"true" '. This fixed stuff for me on Ubuntu 14.04.2 and in manjaro too.
I had tearing problems with freshplayer, smplayer, and html videos in browsers.

**Comment by cyberalex4life** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/2423189/8893515/5bdced24-339b-11e5-890c-7a2a6f4771e9.jpg)

**Comment by TheIntelligentMan** [comment]
Cyberalex4life,nope I'm using an AMD CPU so I think it's not my CPU that's causing this.

**Comment by cyberalex4life** [comment]
Have you tried some workarounds for AMD? Adobe Flash 11.2 didn't have tearing with no workaround in my case. It's just a guess, try see if HTML video player has tearing on some HD/HD Ready videos. If it tears you may need a global workaround

**Comment by cyberalex4life** [comment]
I read now the first comment about HTML not tearing

**Comment by i-rinat** [comment]
I've just implemented delayed rendering which I talked about in 491b5b47c742b56105a18519420f0ed58bf36ac9. Could you try again?

Now there is separate thread which main task is to wait vertical refresh events.

**Comment by TheIntelligentMan** [comment]
Latest patch fixed it so I'm closing it.

**Comment by i-rinat** [comment]
So does it really help?
I wasn't able to eliminate tearing at all on my machine, tearing line on top of the screen is still there.

**Comment by TheIntelligentMan** [comment]
Tearing is now gone.I switched to Kwin from Compiz so that might have fixed the video tearing issue I was having with your plugin.
