### ISSUE TITLE
Black fullscreen in KDE, but not in IceWM

### ISSUE THREAD

**Issue by fredlwm** [i-rinat/freshplayerplugin#229]
I'm using up to date Arch Linux 64-bit and compiled the latest git. With KDE 5, I get a black window (nothing freezes) entering fullscreen with latest stable Firefox from mozilla.org. I tried to change settings in freshwrapper.conf (enable_3d, enable_hwdec, quirk_plasma5_screensaver, enable_vaapi and enable_vdpau) and in Flash (18.0.0.24 from latest stable Google Chrome), but all I got were rectangles.

I'm using an onboard video (HD 3000) with the default Radeon drivers.

Testing with IceWM, it worked fine, but I have no idea where the problem lies. This is the first time I install the plugin, so I've no idea if it worked in the past.

**Comment by edishtron** [comment]
I'm using up to date Arch as well. 

Up until yesterday it was working fine with 25d58b3 of freshplayerplugin.

What changed, I updated to the latest google chrome Arch offers (google-chrome 43.0.2357.132) and KDE Frameworks 5.12.0.

So i guess most likely an issue with KDE.

**Comment by fredlwm** [comment]
Well, I wasn't using up to date. It was from a week ago. I just updated it, KDE moved from 5.11.0 to 5.12.0, but it didn't change anything.

Maybe a KDE (3D / older hardware) issue, but the plugin works fine natively in Google Chrome 43.0.2357.132.

**Comment by mrbumpy409** [comment]
I am running into a similar problem, although in my case, fullscreen video isn't black, but instead appears as a bunch of colored rectangles. Here's a screenshot:
![fullscreen-corruption](https://cloud.githubusercontent.com/assets/6825789/8634881/f92a0368-27d0-11e5-894d-a06e8e5169e7.png)

I discovered, however, that if I set the fullscreen width and height to anything other than my screen's actual size (either smaller or larger), the video appears correctly (albeit at the specified size). My screen is 1280x960. If I set the fullscreen width/height to 1024x768, then the fullscreen video appears at 1024x768, anchored to the top-left corner of the screen (the rest of the screen is black). However, it should be noted that the mouse hotspots are still scaled to the screen's full size, so if I want to exit a fullscreen YouTube video, for example, I must click the bottom right-hand corner of the screen, even though the fullscreen button is being drawn closer to the middle of the screen.

So, the workaround for me for now is to set the following options in freshwrapper.conf:
fullscreen_width = 1280
fullscreen_height = 959

This makes the video one pixel too short, but this really isn't noticeable.

I should also note that I disabled 3D in freshwrapper.conf to avoid the black window issue.

** My System **
OS: Kubuntu 14.04 64-bit w/ KDE SC 4.13.3
Motherboard: ASRock X58 Extreme3 (Intel X58 chipset)
CPU: Intel Core i7 930 (2.8 GHz quad-core)
RAM: 12GB DDR3
Video: NVIDIA GeForce 7900 GS w/ 256 MB RAM (PCI Express)
Linux Kernel: 3.13.0-57-generic
NVIDIA video driver: 304.117
Screen #1 Resolution: 1280 x 960 @ 100 Hz
Screen #2 Resolution: 1280 x 1024 @ 75 Hz

**Comment by fredlwm** [comment]
Thanks. I had it set to 0 and 0. I changed it to 1920 and 1080 to no avail, but it worked with 1920 and 1079.

3D is still enabled.

**Comment by i-rinat** [comment]
From geometry trick helping I can guess it have something in common with issue #227. I've just pushed to `master` branch a patch b100b9ccbc4cf0361b759f6918d563cc6c2666ec which should deal with it. Could you test again?

**Comment by fredlwm** [comment]
Updating git, setting to 0 and 0, 1920 and 1080 or 1920 and 1079, I now get it right or the black window.

Before, it'd always work with 1920 and 1079, and never with the others.

**Comment by i-rinat** [comment]
> I now get it right or the black window.

Sorry, I don't get it. Are you saying it doesn't work now with any settings at all?

**Comment by fredlwm** [comment]
I randomly get it working or the black window. I tested a few minutes ago, and I had to go fullscreen a few times to get it working. The other times, it was the black window.

**Comment by karolgrudzinski** [comment]
I have very simillar problem, but I don't get black window. I can see that video is playing in top-left corner, but is really small (10px in width or something like that). In about 10% of cases fullscreen is working normally. Your recent changes in b100b9ccbc4cf0361b759f6918d563cc6c2666ec hasn't changed anything. enable_hwdec also don't make any difference.
My pc: i3 2.4GHz, 8GB RAM, GeForce 310M (1GB RAM) drv 337.25, KDE 4.14, Firefox 39, Linux-4.1.2. I'm reinstalling freshplayer daily by gentoo live ebuild.

**Comment by jyrkive** [comment]
I also have the "super-small video in fullscreen mode" problem. As above, b100b9c didn't change anything.

My system: Intel Core i5-4430, 16 GB RAM, GeForce GTX 960, [siduction](http://distrowatch.com/table.php?distribution=siduction), SeaMonkey 2.33.1, NVIDIA driver version 346.82, KDE Plasma 5.3.2, KDE Frameworks 5.12.0.

**Comment by trancephorm** [comment]
Kubuntu 14.04 fully updated, Flash video in fullscreen is just a small rectangle in the top left corner.... Played with freshwrapper.conf file, it's wird but here's what fixed it in my case: changed device_scale parameter to 1.1

**Comment by karolgrudzinski** [comment]
Never mind. Solution really is a few comments above. Everything works (also HWDEC) if video size is slightly smaller than screen resolution. I've fixed it with simple change in code:
```
diff --git a/src/ppb_flash_fullscreen.c b/src/ppb_flash_fullscreen.c
index b9c3a1d..137e2e3 100644
--- a/src/ppb_flash_fullscreen.c
+++ b/src/ppb_flash_fullscreen.c
@@ -100,8 +100,8 @@ update_instance_view_comt(void *user_data, int32_t result)
     v->rect.point.x = 0;
     v->rect.point.y = 0;
     if (pp_i->is_fullscreen) {
-        v->rect.size.width = pp_i->fs_width / config.device_scale;
-        v->rect.size.height = pp_i->fs_height / config.device_scale;
+        v->rect.size.width = (pp_i->fs_width - 1) / config.device_scale;
+        v->rect.size.height = (pp_i->fs_height - 1) / config.device_scale;
     } else {
         v->rect.size.width = pp_i->width / config.device_scale;
         v->rect.size.height = pp_i->height / config.device_scale;
```

**Comment by rdots** [comment]
>if video size is slightly smaller than screen resolution. I've fixed it with simple change in code

Hello, [karolgrudzinski](https://github.com/karolgrudzinski) I'm fairly new to code and would like to know how to make change the source code to your changes.
Thanks.

**Comment by i-rinat** [comment]
Hi. I've made couple of changes regarding fullscreen geometry in 08ea38edd113f44352e29d07eb4b8a29148d235e and 8c3a2dac580069cbb1224c8d1f1446a899647551. Could you check again?

**Comment by rdots** [comment]
>[08ea38e](https://github.com/i-rinat/freshplayerplugin/commit/08ea38edd113f44352e29d07eb4b8a29148d235e) [8c3a2da](https://github.com/i-rinat/freshplayerplugin/commit/8c3a2dac580069cbb1224c8d1f1446a899647551)

I'll try to recompile from git and will reply the results

**Comment by rdots** [comment]
i can confirm the commits from [08ea38e](https://github.com/i-rinat/freshplayerplugin/commit/08ea38edd113f44352e29d07eb4b8a29148d235e) [8c3a2da](https://github.com/i-rinat/freshplayerplugin/commit/8c3a2dac580069cbb1224c8d1f1446a899647551) fixes the problem 50% of the time for me, usually if a flash object issued a super small screen whilst the screen black, I had to exit fullscreen (waited 5 seconds) and reinitiated fullscreen for it to work again. Other than that it works and I appreciate the changes, [i-rinat](https://github.com/i-rinat).

**Comment by i-rinat** [comment]
And also broke fullscreen on my machine. So I reverted last commit.

**Comment by karolgrudzinski** [comment]
Hahaha @i-rinat your revert-commit broken FS for me again :-), so I'll just stick with my "fix".

**Comment by i-rinat** [comment]
Here is cumbersome combination of weirdness.

First, PepperFlash player have special callback, `DidChangeView` which should be called when size of plugin changes. It's the way Pepper plugins get information about their new size. Odd thing is PepperFlash only honors **first** call and ignores others.

Next, the way fullscreen transition works in X environment. Client program adds atom `_NET_WM_STATE_FULLSCREEN` to `_NET_WM_STATE` window property. Window manager listens for such changes and resizes window to fit fullscreen. Some window managers (metacity) also require values like `_NET_WM_STATE_MAXIMIZED_VERT`, otherwise titlebar/taskbar stays visible.

The trickiest part is to link those two parts, since I can't see a reliable way to determine fullscreen size. Say, initial window size is set to 10x10 pixels and single monitor have resolution 1366x768 px. Then in xfwm4, application will get three ConfigureNotify events with sizes 10x10, 1366x768, 1366x768, and one Expose of 1366x768+0+0. In "awesome" it will be ConfigureNotify of sizes 10x10, 1366x10, 1366x768, and then one Expose 1366x768+0+0. One can think "hey! I see a pattern! Let's use Expose event and send DidChangeView when it arrives!". And then E17 comes into play. Instead of one Expose event it issues half a dozen, something like 200x748+0+0, 200x748+200+0, 200x768+400+0, and so on with final lower bar of 1366x20+0+748.

From previous similar bugreports I've elaborated a procedure to find correct size, and now it stopped working in KDE. I'm sitting here, trying various combinations and thinking, what desktop environment will next change break.

**Comment by i-rinat** [comment]
I've just added a patch (491b5b47c742b56105a18519420f0ed58bf36ac9) which changes the way fullscreen geometry is determined. Could you try again?

**Comment by fredlwm** [comment]
I think it's working fine now, but I'm not sure it the following is unrelated. Suddenly, while testing, my screen became black. In my logs, there's:

traps: plugin-containe[598] general protection ip:7f4f9d121b2a sp:7f4f863fdbc0 error:0 in libX11.so.6.3.0[7f4f9d0e6000+13b000]

**Comment by i-rinat** [comment]
> but I'm not sure it the following is unrelated

It could related indeed, as changes were Xlib-related. I'm not able to reproduce any of such crashes, even under Valgrind.
Does it happen often? Is there any specific way to reproduce it?

> traps: plugin-containe[598] general protection ip:7f4f9d121b2a sp:7f4f863fdbc0 error:0 in libX11.so.6.3.0[7f4f9d0e6000+13b000]

Unfortunately, I don't have experience on handling such pointers, I much better at using gdb. Exact Xlib (sometimes it's called libx11) package and distribution version could help to determine which function address `+13b000` is pointing at.

**Comment by fredlwm** [comment]
No, it happened once, when switching to and from fullscreen, but I didn't test that much yesterday. There was also

kernel: plugin-containe[10986]: segfault at 7fee39ab6fb0 ip 00007fee39ab6fb0 sp 00007fee3b41ac68 error 14

some time later, I think when I closed Firefox.

libX11 is 1.6.3-1 from https://www.archlinux.org/packages/extra/x86_64/libx11/

**Comment by i-rinat** [comment]
That address points into `XSendEvent()` internals, most probably crash happens at `LockDisplay (dpy);` statement. It checks for NULL, so there is definitely no NULL-pointer dereference. But there could be use-after-free condition, where at some point `Display` structure is freed, but still used in `delay_thread()`. Firefox is poisoning freed memory, so that kind of bugs are exposed early.

I'll look into how to prevent such condition.

**Comment by tancrackers** [comment]
I'm on KDE 4.14, but I'm having a problem with fullscreen freshplayer flash. It's black, but I noticed something: The video is REALLY tiny, and in the upper left corner. Look very closely in my attached screenshot.

Also, this happens when it's just the flash video going fullscreen, on my end. If the website itself goes fullscreen in order for the video to go fullscreen, then all is good.
Examples:
When only the Flash videos go fullscreen:
http://espn.go.com/
http://cine.batanga.com/7699/actores-que-hacen-lo-mismo-en-todas-las-peliculas

When the site goes fullscreen in order for the video to go fullscreen:
http://www.imdb.com/
http://sport.tvp.pl/wideo
In these ^, Firefox gives a prompt to give the webpage permission to go fullscreen, which is not the case for ESPN, for eg. In these sites, the videos load fine when in fullscreen.
![screenshot77](https://cloud.githubusercontent.com/assets/1408654/9010350/62b37f8c-3774-11e5-8840-dce21ec59708.png)

**Comment by i-rinat** [comment]
@tancrackers, are you using most recent version, 8aced7539f00ac2b4624bcc79f7c7fec98272807?

**Comment by tancrackers** [comment]
I apologize. I was running this package:
https://aur.archlinux.org/packages/freshplayerplugin/

I tried this:
https://aur.archlinux.org/packages/freshplayerplugin-git/
using that latest commit, and everything works!
Question, where is the "stable" numbering for this? The AUR packages confuse me.

**Comment by i-rinat** [comment]
There are no stable versions in a common sense :-(
Maintaining stable branches and providing bugfixes there is quite hard, so I just put tags in a linear history. Usually that happens when I don't see any major bugs ruining browsing experience. Last was "v0.3.1" (you can see them [here](https://github.com/i-rinat/freshplayerplugin/releases)).

Then if somebody encounters a bug, and I manage to fix that, patch goes to `master` branch.

**Comment by jyrkive** [comment]
Fullscreen works fine for me with latest git. Thank you! :)
