### ISSUE TITLE
The plugin reports the wrong flash version when using pepperflash-nonfree

### ISSUE THREAD

**Issue by stof** [i-rinat/freshplayerplugin#246]
Flash is reported as being at version 13.1.2.3 while pepperflash-nonfree provides Flash 18 currently

**Comment by i-rinat** [comment]
PepperFlash doesn't have an API for acquiring version as NPAPI plugins do. Instead, version is taken from `manifest.json` file near `libpepflashplayer.so`. If there is no such file, dummy version `13.1.2.3` is used.

Only "version" attribute is used, therefore following should be enough:
```json
{
    "version": "18.0.0.209"
}
```

**Comment by i-rinat** [comment]
Sometimes you need update modification date of `libfreshwrapper-pepperflash.so`, or delete `pluginreg.dat` file from Firefox profile directory. Otherwise Firefox will continue to use cached version.

You can get to the profile directory by pressing "Open Directory" button in "Application Basics" table.
