### ISSUE TITLE
Firefox Click-To-Play not working with Flash 18

### ISSUE THREAD

**Issue by kamil7x** [i-rinat/freshplayerplugin#249]
Hi,

I am using Kubuntu 15.04, with Firefox Beta (actually 40). I have set Click-To-Play function, because i don't want flash ads to play automatically etc. 
With Flash 17, it was working okay, but now. When i click Activate Plugin, i have no response. Normally i should have popup with two buttons ("allow now, allow always" or something like that) and video should play.
Does someone experience similar issues?

**Comment by i-rinat** [comment]
I've seen similar behavior. Zero reaction on pressing on gray box where Flash movie. Also button in the address bar (they call it Awesome Bar) didn't work. It appears by itself, and solves by itself. I don't think I can do anything in Freshplayerplugin, since any code I wrote there gets executed only after you succeed in pressing "Allow" button.

So in other words, I believe it's a Firefox issue.

If you have any idea about how it can be fixed in Freshplayerplugin code, please let me know. Whole software bundle is big, so I easily could miss something.

**Comment by kamil7x** [comment]
For me, I found that I have enabled Shumway extension, I disabled it and it works ok. But I am not sure if it is only reason of that.
