### ISSUE TITLE
i'd like to know if there is a way to know freshplayerpluin's version informations ?

### ISSUE THREAD

**Issue by redhatlinux10** [i-rinat/freshplayerplugin#253]
i do not mean the related package's informations if *freshplayerpluin* being installed through a package manager.
i mean is it possible to get *freshplayerpluin*'s version informations from `about:plugins` page or video-playing context just like adobe flash player's version info ?

**Comment by i-rinat** [comment]
No, placing version information into `about:plugins` page is not possible.

The reason is, different websites use various techniques to determine Flash player presence and its version. They usually take string representation, `Shockwave Flash 18.0 r0` and parse the string. Some of them require string to begin with `Shockwave Flash` and take third and forth elements after splitting string at spaces to determine version. Others take two last elements for version.

I used to add a description ([here is screenshot from one of the first version](http://4.bp.blogspot.com/-5_zvikmofJE/U3slTxGVwOI/AAAAAAAASxE/GMHEG5bssq8/s1600/fresh-plugin-firefox.png), look at description string). But then removed, since it caused compatibility issues. See #11 for example.

**Comment by i-rinat** [comment]
I think it's still possible to add some information to context menu, just after "About Flash..." line.

But it's still unknown what write there. Something like version of previous stable release? But there could be changes after that and version would be the same despite different behavior, if, say a bug was fixed in `master` branch. Version detection via some scripts won't work when building outside of repository. From release tarball, for example.

**Comment by redhatlinux10** [comment]
I have some suggestions. with a release tarball, `freshplayerplugin 0.3.1` would be good. and this version info can be retrieved from a version field in a version file( such as `REL_VER_INFO` in `version.h`), the version field 's value is manuallly or automatically specified when you mark this revision as a release version.
with the master branch, `freshplayerplugin pre-0.3.2-20150816` would be good and 0.3.2 equals `REL_VER_INFO`+0.0.1. `20150816` comes from another version field in the  version file(such as `COMMIT_TIME` in `version.h`) . `COMMIT_TIME` is automatically generated when  committing and filled into `version.h`. this maybe can be accomplished with a git-pre-commit-script.

**Comment by i-rinat** [comment]
Although manually added "big" version is fine, I feel unease about changes to `version.h` coming with every commit.

**Comment by i-rinat** [comment]
Implemented in 5b135bc49d3ddb5120daecd1337663b1f7e4771e and 4b4ebf464355b7da87b8f411ce2b8e29e809703f.

It's disabled by default, and to enable, one must add `show_version_info = 1` to `~/.config/freshwrapper.conf`. Version will appear in a Flash context menu as a separate grayed item.
