### ISSUE TITLE
full screen not working

### ISSUE THREAD

**Issue by je-vv** [i-rinat/freshplayerplugin#254]
When a full screen is attempted, though the screen goes full and black, the image reduces to a tiny upper left corner coloured dots...

It's like that for about last 2 or 3 releases.

**Comment by i-rinat** [comment]
Which version are you using? Is it v0.3.1 or version from tip of the `master` branch?

**Comment by je-vv** [comment]
v0.3.1

**Comment by i-rinat** [comment]
Very similar issue (#229) was solved recently, but changes were added after v0.3.1 release.

I've just put another tag, v0.3.2. Please try it (or version `master` branch, they are the same at the moment).

**Comment by je-vv** [comment]
Though I do not use KDE (neither any DE), but rather plain Fluxbox WM, It worked out!

And as I use Arch, I just had to "yaourt -Sayu", and got the new package version, :-)

So you can close this.

Thanks a lot,

**Comment by i-rinat** [comment]
Issue wasn't caused by KDE exclusively. Just PepperFlash was updated and its behavior slightly changed. Together with differences in going-to-full-screen procedure in different window managers that triggered a dormant bug. It's still there, by the way. I just hope 300 ms is enough to open fullscreen window for any WM. (Delay can be changed via editing of configuration file.)

Ideal solution would be to accept all size changes in PepperFlash, not only the first one. But since its code is closed, the only way solve it is to workaround it.

**Comment by je-vv** [comment]
OK, great support Rinat...  And thanks a lot.
