### ISSUE TITLE
Flash has heavy graphic glitching under 0.3.2 when switching to another task and back.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [i-rinat/freshplayerplugin#258]
Flash has heavy graphic glitching under 0.3.2 when switching to another task and back. I was watching a Live Stream on Youtube that required Flash, I switch to another window, and to preform another task, then switched back. There was severe graphical errors, with part of the chat room and window elements from other tabs where other showed up. This did not happen in 0.3.1

**Comment by i-rinat** [comment]
I never seen anything like that, so can only guess what happens.

If plugin uses `PPB_Graphics3D` interface (used for accelerated rendering), an offscreen pixmap is created. Every drawing is performed on that offscreen pixmap. Then, when browser calls `NPP_HandleEvent`, I copy that pixmap contents to provided drawable. For windowed instances `NPP_HandleEvent` is called from a separate X event loop inside freshwrapper itself. That makes either double or triple copying, depending on mode used. But that's better than flicking.

When one switches active tab and plugin instance becomes visible, actual data are taken from backing offscreen pixmap. If for some reason its content is damaged, you'll see that damaged picture. Then, after PepperFlash repaints viewport, it will be "fixed". 

The issue you're talking about is very likely to be caused by DDX driver. If drivers decides to save memory on offscreen pixmaps, it can discard their contents and reallocate it on next use. For X Windows that saving makes sense. Discarding data of all Drawables, both Windows and Pixmaps, will result in similar glitches.

If you can reproduce the issue often enough, could you test whenever v0.3.1 doesn't have that issue? If that's the case, it would be nice if you use `git bisect` to find which commit if the breaking one. Perhaps I can figure how to workaround it.

**Comment by Zombie-Ryushu** [comment]
It is very random when it happens. I'll see if I can't try and setup a situation where it happens  every time.

**Comment by i-rinat** [comment]
Code in freshwrapper request a backing store for windows it creates. So the bug "should never happen". But it happened. And I don't now nor how to reproduce it, neither how to fix it.

**Comment by i-rinat** [comment]
By the way, does it still happen?

**Comment by Zombie-Ryushu** [comment]
I don't think so.
