### ISSUE TITLE
double-click switch fullscreen not working

### ISSUE THREAD

**Issue by baragoon** [i-rinat/freshplayerplugin#259]
Hi!
Instead of activating fullscreen mode double-click just make pause-unpause.
Tested with version 0.3.1-r2 from gentoo portage and current from git.

**Comment by i-rinat** [comment]
Hello.
As far as I know, there is nothing in PPAPI about double clicks. Every click is passed to the plugin as a separate event, and plugin determines whenever those were a two separate click, or one double click. Since PepperFlash determines that on its own, its settings can differ from system ones.

Perhaps, you are not clicking fast enough? I've just tried it on Youtube player, and it definitely goes fullscreen on double click. However, changing system settings (to 1 second, for example) have no effect on PepperFlash.

**Comment by i-rinat** [comment]
Oops, I was wrong, there is actually `click_count` parameter.

**Comment by i-rinat** [comment]
Despite existence, `click_count` parameter have no effect at all.

**Comment by baragoon** [comment]
Ha, I see... doubleclick works on youtube but doesn't works on some russian online films storage like seasonvar or filmix. But everything works fine on this sites if I using google chrome with pepper flash.
Also it works with adobe flash.

**Comment by i-rinat** [comment]
Indeed, player on seasonvar doesn't go fullscreen on double click. I'll take a deeper look.

**Comment by jscinoz** [comment]
For what it's worth, I'm also having issues relating to double-clicks in Flash content not being detected when using freshplayerplugin with Firefox, whereas the same underlying pepper flash version works correctly in Chromium.

**Comment by i-rinat** [comment]
It turned out there are two ways of handling doubleclicks in Flash. One way is obvious measuring time between single clicks and other is `MouseEvent.DOUBLE_CLICK` event. It's disabled by default and doesn't work until explicitly enabled. Perhaps that's the reason both ways are used in the wild.

For second method, `click_count` parameter does matter. I've fixed behavior in 7ff6aea8ff6d272d9b83702fc34089b97167fdba. Player on seasonvar site does go to fullscreen on double click now.
