### ISSUE TITLE
twitch.tv: New player controls don't show up.

### ISSUE THREAD

**Issue by Ziemas** [i-rinat/freshplayerplugin#273]
twitch.tv just switched to using HTML5 player controls together with flash for video. For some reason the player controls don't display when using freshplayerplugin.

**Comment by Pazns** [comment]
Same observation.
When hot-disabling the plugin, the video is replaced with a grey block (as expected) and controls magically work again, like if they were hidden behind the whole time, or if the hover event wasn't triggered.

**Comment by i-rinat** [comment]
What mode plugin working in?
To find out, open developer console (Ctrl-Shift-i, then select Console tab) and enter there:
```
document.querySelector("#player-flash-0 param[name=wmode]").value
```

You also can use page Inspector to find `<object>` tags and check wmode parameter value.

I expect it to be either "transparent" or "opaque". In those cases HTML page elements can be placed on top of plugin. But if mode is "direct", "window" or "gpu", plugin will be drawn on top of any other content.

**Comment by madovsky** [comment]
> But if mode is "direct", "window" or "gpu", plugin will be drawn on top of any other content.
well i-rinat, not entirely true if z-index layres are used with CSS ;)

**Comment by Pazns** [comment]
@madovsky In fact I tried to fool Flash a bit, playing with z-index property, but no luck, nothing happened. Maybe I did something wrong ?

Anyway, the issue appears with FreshPlayer-over-PepperFlash and not with FlashPlayer plugin.
A CSS trick is out of context, even if it could solve something.

**Comment by madovsky** [comment]
@Pazns  the thing I know is use Transparent or GPU make the entire browser slower and by the way make all the streaming cheesy. I avoid to use these 2 settings since 6 years in all my projects preferring "window" or "opaque" and playing with z-index successfully.
I guess your problem comes from the layer instance levels. you should start from the highest which can be a DIV or else (the max layer is 65535) to the lowest which can be the background of your HTML page (-1 or 0). you flash must be in the middle wherever you like

**Comment by i-rinat** [comment]
@madovsky,
hmm, it works indeed. I just remember when I used userscript which changed all Flash instances wmode parameter to window (to allow Flash to use VDPAU), it often broke HTML controls which were supposed to be drawn above plugin content. And according to [that article](https://helpx.adobe.com/flash/kb/flash-object-embed-tag-attributes.html#main_Browser_support_for_Window_Mode__wmode__values) layering in windowed mode works only on subset of platforms. To make it work reliably, one have to use `opaque` or `transparent`.

By the way, one of the reasons to create freshplayerplugin is to use hardware acceleration whenever possible. NPAPI Flash uses VDPAU only in windowed mode (window, direct, gpu), and falls back to software scaling in windowless mode (opaque, transparent). That was the reason of high CPU usage. In freshplayerplugin I use offscreen X Pixmap, and then combine pictures in a separate step. That helps to use hardware accelerated rendering in any mode.

**Comment by madovsky** [comment]
indeed, but depends what you are doing is for private or public project. some users don't have any GPU accelaration or it's very buggy with flash. for sure the best would be to code a page that check if GPU accelerator is available and fall back to direct if fails which is possible in AS3

**Comment by Pazns** [comment]
Indeed, Twitch seems to run Flash with "direct" wmode.
So, how can one force "opaque" wmode (I take Hitbox.tv choice for reference) on Twitch ?

**Comment by i-rinat** [comment]
> Twitch seems to run Flash with "direct" wmode

Maybe you have an userscript which changes `wmode`? Or a browser extension?

**Comment by Pazns** [comment]
I will try in failsafe mode.

**Comment by Ziemas** [comment]
Some testing i did:

On firefox with freshplayerplugin `document.querySelector("#player-flash-0 param[name=wmode]").value` returns `"direct"` and controls are not visible.

On firefox with NPAPI flash it returns `"transparent"` and controls are visible.

On chromium it returns `"direct"` and the controls are visible.

**Comment by i-rinat** [comment]
OK, found it. Player page on Twitch contains the following code:
```javascript
        m = function() {
            var e = "application/x-shockwave-flash",
                t = navigator.mimeTypes;
            if (t && t[e] && t[e].enabledPlugin) {
                var n = t[e].enabledPlugin.filename;
                return n.match(/pepflashplayer|Pepper/gi) ? "ppapi" : "npapi"
            }
            return v() ? "unknown" : ""
        }
```

and later function m() is used to determine which wmode to use:
```javascript
 "ppapi" === m() ? d.wmode = "direct" : d.wmode = "transparent";
```

I have both NPAPI Flash and freshwrapper installed. And because of that `navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin.filename` returns `libflashplayer.so`. Twitch's script decides that it's a NPAPI plugin and uses "transparent". But apparently on your machines you have only freshwrapper installed, so that long line returns `libfreshwrapper-pepperflash.so` instead. As you can see, there is "Pepper" substring in it, so script decides it runs under Chromium-based browser, and sets "wmode=direct".

PPAPI doesn't have notion of plugin mode, there is only one mode possible. And whenever mode is, layering is supported, so controls works in Chrome too, regardless of "direct" wmode.

I think renaming `libfreshwrapper-pepperflash.so` to something without "pepper" substring will fix issue.

**Comment by Ziemas** [comment]
Yes, renaming it does indeed solve the issue.

**Comment by Pazns** [comment]
renaming libfreshwrapper-pepperflash.so to something without "pepper" substring will fix issue.

It absolutely works.

I'm thinking about renaming "libfreshwrapper-pepperflash.so" to "libflashplayer.so" to fool websites and ensure they understand it as a NPAPI plugin, which it is actually.

**Comment by i-rinat** [comment]
> What do you think ? Is it a wrong idea ?

I don't know what to think. Previously I thought that recommendations on the net about removing NPAPI Flash player and use only freshplayerplugin were "wrong". I have both installed, and Firefox always uses most recent version. There were no issues. But then I found that at least on one site (I think it was GYAO) scripts are examining only first plugin for particular MIME-type, and it happen to be 11.2. Site explicitly refused to continue, although more recent plugin version were available. And now having 11.2 actually prevented me from encountering the bug.

Maybe it's not a bad idea, to mimic a file name too.

I'm going to change file name from `libfreshwrapper-pepperflash.so` to `libfreshwrapper-flashplayer.so` in the repository. It should work, since there are no "pepflashplayer" or "pepper" in it. Changing it to `libflashplayer.so` can confuse users (me too!), without any noticable benefit.

**Comment by madovsky** [comment]
very good idea indeed,
but sshhhht, guys keep your mouth closed
out of this thread ;)

**Comment by madovsky** [comment]
or if you don't need to use "lib" why not
lashplayer.so to avoid any crooks rights? ;)

**Comment by madovsky** [comment]
Or maybe is there a (more humble) way to
change on the fly when the plugin is installs
the mime app from the browser?

**Comment by Pazns** [comment]
@madovsky : « but sshhhht, guys keep your mouth closed out of this thread ;) »

Yeah, it needs to be an undercover flash plugin !
_Operation Flashplayer : Wrapper Rising_ .

**Comment by madovsky** [comment]
@pazns
It recalls me Gnash project ;)
anyhow I think the best (to avoid men in black) ;)
is to find a way to modify on the fly (with of course
an invite warning telling that the plugin needs to
change the mime blabla) and live freshplayer called
fresh ! or shlafplayer is good too! (shlaf is night in German)

**Comment by i-rinat** [comment]
Binary renamed to `libfreshwrapper-flashplayer.so` in d561c8410e3d93fda6d5866cfe93f33fae24e3d2.

**Comment by ahjolinna** [comment]
I just tested the git version and the controls works now. @i-rinat : maybe u should release a new 'stable' version for distors, I know that at least chakraOS doesn't like to use git versions...and adding patches (at least if there are many) is such a pain in ...

**Comment by i-rinat** [comment]
> maybe you should release a new 'stable' version

Sure, why not: https://github.com/i-rinat/freshplayerplugin/releases/tag/v0.3.3
