### ISSUE TITLE
[fresh] [warning] failed to parse configuration file

### ISSUE THREAD

**Issue by gnaag** [i-rinat/freshplayerplugin#279]
When I run nuvola-player (wrapper for web based muisic streaming services) that is based on webkit2gtk there is this warning while loading of freshwrapper. It does not depend whether those files exists or are filled with default config (from github example config file). In firefox freshplayer works well (even though I do not know if there are any warnings).

> **[fresh] [warning] failed to parse configuration file /home/$user/.config/freshẃrapper.conf, trying/etc/freshwrapper.conf (enabled)**
> /usr/lib/mozilla/plugins/libfreshwrapper-flashplayer.so
> [fresh] [warning] failed to parse configuration file /etc/freshwrapper.conf

This is dump from nuvolaplayer3 -D

> [Runner:DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: [fresh] [warning] failed to parse configuration file /home/gnaag/.config/freshwrapper.conf, trying /etc/freshwrapper.conf (enabled, not flash) at /usr/lib/mozilla/plugins/libfreshwrapper-flashplayer.so: [fresh] [warning] failed to parse configuration file /etc/freshwrapper.conf

The important part is that freshplayer is not considered to contain a flash player, therefore it is not used. According to Nuvola player and some users' reports, Fresh player is supposed to work with nuvola.

**Comment by i-rinat** [comment]
Those messages are not errors, but just notifications about missing configuration file. Freshwrapper should work fine without any config file, using default values. I'll remove warnings, their presence is confusing indeed.

> `/home/$user/.config/freshẃrapper.conf`

To get configuration path I first check `XDG_CONFIG_HOME` environment variable. If there is no such variable, use `HOME` and append `/.config`. Looks like one of those variables on your system contains `$user`. Not a value of variable `user`, but literally `$user` with a dollar sign.

I don't think expansion of shell variables should be performed in freshwrapper, it's better to figure out why shell didn't expand them on your system.

**Comment by i-rinat** [comment]
Warnings removed in dfa3331930f06d642d35098a1ba604b8d0013757.

**Comment by i-rinat** [comment]
As for 
> The important part is that freshplayer is not considered to contain a flash player, therefore it is not used.

I can't say anything for sure. From warning messages I could say freshwrapper is loaded. But maybe it can't find PepperFlash? If you have it in unusual location, and specify path in `freshwrapper.conf`, it could be that `$user` path issue that prevents config from loading.

But anyway, it should at least show placeholder where flash plugin is used on a page.

**Comment by gnaag** [comment]
I am sorry about the confusion with the $user. I have deliberately changed my username to $user to make the post more general. 

As for freshwrapper not being considered as flash, in firefox it is working fine. First I tried it with google-chrome installed, afterwards, I even tried 
> sudo apt-get install pepperflashplugin-nonfree
> sudo update-pepperflashplugin-nonfree --install

But it did not make any difference. I am going to ask nuvola devs whether they changed something in detection of flash. In march the issue about support fresh player appeared to be solved according to [launchpad #1322954](https://bugs.launchpad.net/nuvola-player/+bug/1322954). There was even an image as a [proof](https://launchpadlibrarian.net/187863928/nuvola_player_3_fresh_player.png) :)

**Comment by gnaag** [comment]
Funny thing is that these notifications happens even when I have these files. I have created them with the default one found on github. Both of them /home/gnaag/.config/freshwrapper.conf and /etc/freshwrapper.conf point to
> pepperflash_path = "/opt/google/chrome/PepperFlash/libpepflashplayer.so"

and there the flash is. So I don't know why it cannot read  / parse them, when they are there

**Comment by i-rinat** [comment]
If you have PepperFlash at `/opt/google/chrome/PepperFlash/libpepflashplayer.so` and no configuration file, it should work anyway, since freshwrapper tries [several paths](https://github.com/i-rinat/freshplayerplugin/blob/dfa3331930f06d642d35098a1ba604b8d0013757/src/config_pepperflash.c#L28).

Perhaps plugin process is sandboxed and that prevents freshwrapper from both reading configuration and loading PepperFlash?

**Comment by i-rinat** [comment]
What distribution (and what version) do you use? Are there any external repositories used?

**Comment by gnaag** [comment]
I use webupd8 repo version (0.3.3+git20151006~webupd8~vivid) on ubuntu 15.04

**Comment by i-rinat** [comment]
Oh. Here is what's happened. Webkit2gtk uses a trick to detect a plugin version. Since it uses a separate process to host plugins, there is a code which asks plugin its version and then prints it to standard output. Main browser process intercepts output and expects first line to contain plugin version. But gets that warning string from freshplayerplugin. Browser then decides the plugin it non-functional, and caches that information in `~/.cache/webkitgtk/plugins`. So then even if you create `~/.config/freshwrapper.conf`, freshwrapper itself is never called again. That's why that message kept showing.

Try to delete `~/.cache/webkitgtk/plugin` and restart Nuvola player.

It should also help to change modification data of `/usr/lib/mozilla/plugins/libfreshwrapper-flashplayer.so`. One can do it by calling following:
```
$ sudo touch /usr/lib/mozilla/plugins/libfreshwrapper-flashplayer.so
```
I didn't check, but I expect Webkit2gtk to try to reload plugin once its date changed.

**Comment by gnaag** [comment]
Thank you, I will have a look after weekend. Now I don't have a regular
computer with me.
Dňa 16.10.2015 14:20 používateľ "Rinat Ibragimov" <notifications@github.com>
napísal:

**Comment by i-rinat** [comment]
Added a Webkit2gtk detection in ad5b5069f1d0d5b9acfcadacdc605840f89d6166 to prevent any messages from getting to standard output. That should prevent similar issues in future.

However, it's still required to flush plugin cache by deleting `~/.cache/webkitgtk/plugin` if issue was already triggered.

**Comment by Coeur-Noir** [comment]
Hello !

Is this the same issue : https://bugs.launchpad.net/freshplayerplugin/+bug/1506968 ?

And so, same solution ?

**Comment by i-rinat** [comment]
Hi @Coeur-Noir.
Message by itself is not a error. It's just a message about freshplayerplugin tried to read configuration file while there were no any. It has no effect when you use Firefox. But anyway, I've changed code so the warning about missing freshwrapper.conf won't be there anymore.

This issue was about browsers that use webkit2gtk library. That's a completely different web browser engine implementation. And it uses a certain trick to get plugin version. NPAPI plugins have a special function exported, that return version string when called. Firefox just loads plugins into main process and calls it there, but Webkit2gtk uses the `WebKitPluginProcess` binary which when launched a certain way, ask plugin for version string and print it to standard output. Browser process intercepts output from plugin host process and uses that line as a plugin description. Usually it prints something like `Shockwave Flash 11.2 v202`. But with freshplayerplugin first line happened to be that `[fresh] [warning] failed to parse...` and so on. So webkit2gtk got confused.

**Comment by Coeur-Noir** [comment]
OK.

So my problem is different : flashplayer does not work anymore in Firefox if I install freshplayerplugin (also from webupd8 repo). As you can see description in LP, it seems to have other error messages, no longer "failed to parse…" but "var is not a string".

It used to work in Firefox using FlashPlayer v19.

If I remove freshplayer plugin, FlashPlayer v11 then works.

**Comment by i-rinat** [comment]
Which site doesn't work?

As far as I can tell, "'var' is not a string" appears when web page creates a hidden Flash movie. Some sites use Flash to make TCP connections, so they create `embed` dynamically, without `src` parameter which is expected to be of string type, but since there is no such parameter, variable keeps `undefined` value, which is not a `string`. Hence the warning. It's harmless.

**Comment by Coeur-Noir** [comment]
http://www.allocine.fr/video/bandes-annonces/

Once again : 
- freshplayerplugin used to work with Firefox on this machine and that above website,
- I don't have this issue on another Ubuntu machine.

**Comment by i-rinat** [comment]
Well, I tried videos on that site. I get both `'var' is not a string` and tcp connection errors, but videos play fine. Messages seem to be irrelevant to the cause of the bug.

As for tcp connection errors, I've seen them before on other Flash movies. Even traced PepperFlash under Chrome. Turned out, they are really trying to connect to local machine, 127.0.0.1. Chrome just doesn't report about failures. Perhaps, that are leftovers from swf debugging stage.

**Comment by Coeur-Noir** [comment]
Mmm.

I don't have problems using Flash with Chrom**ium**.

What remains strange is why this occurs on one machine and not on the other. Both are very similar - as softwares speaking, ubuntu version (14.04 64bits). Repositories differ a bit though…

What should I look at ?

**Comment by i-rinat** [comment]
> What should I look at?

I don't know exactly. I would started from tracing it. (`-DTRACE_ALL=1` in cmake parameters). Running in that mode makes freshwrapper to record every API call, with parameters. Then I try to spot errors in that log. Further actions may vary.

**Comment by Coeur-Noir** [comment]
I (kind of) solved the problem.

I did a sudo ppa-purge xorg-edgers which was the only different repository on this machine compared with the others.

Does it sound a probable cause of the problem to you ? Or just a coincidence ?

**Comment by i-rinat** [comment]
> Does it sound a probable cause of the problem to you?

I've read you messages again and have a question: what did it mean, "broken". If there were only missing graphics, but sound did work and you could start playback blindfold, then yes, different version of X.Org could cause the issue.

I'm still having issues with PRIME on my machine. At first I thought it was something with Mesa (simplified test application had the same issue as freshplayerplugin), but with some debug I figured out that wrong data comes from X.Org. So yes, different versions of graphics stack components could have effect.

**Comment by Coeur-Noir** [comment]
« broken » for example with allocine website, the "player" did not launch at all, just a still black rectangle where there is usually the video. No picture / no sound. But the "content" seems to load as I can "catch" it with flashgot plugin.

Let's say one of xorg-edgers ppa update did something wrong with freshplayerplugin.

**Comment by i-rinat** [comment]
Changed the code (a551ac549c9307672e255cc131fd24fc35d868d9) to handle missing `src` attribute. That could happen if page creates Flash element dynamically, without specifying any source. There will be no `'var' is not a string` messages in that case anymore.
