### ISSUE TITLE
Deviant Art Chat hangs

### ISSUE THREAD

**Issue by Zombie-Ryushu** [i-rinat/freshplayerplugin#281]
Deviant Art Chat hangs when using FreshPlayerPlugin at Opening connection every time, can you reproduce this?

**Comment by i-rinat** [comment]
Works for me.
DevianArt chat uses Flash to make a TCP connection to chat.deviantart.com (resolves to 54.68.114.41 for me) to either port 843 or 3900, or maybe both. And then uses a text-based protocol to send and receive messages.

That part of PPAPI is implemented. I reviewed it couple of times since initial implementation, but didn't find any major errors.

If that doesn't work for you, there are a number of possible error sources. First, DNS service could fail to resolve chat.deviantart.com. Or you may have no connection to that server. Does `ping chat.deviantart.com` give you replies? Second, some firewalls either on your machine or on some machine in the network you are getting internet connection from could block ports 843 or 3900. If you have to use HTTP proxy (some institutions have that), direct connection won't work either. And last I could imagine is ban. (Guys on the channel have proposed to ban me due to frequent reconnects :) ).

**Comment by Zombie-Ryushu** [comment]
Issue was a transient issue with Deviant Art.
