### ISSUE TITLE
Why not add by default freshplayerplugin in the Firefox Linux builds ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [i-rinat/freshplayerplugin#286]
Many persons use chrome on Linux because better flash and because they ignore the existence of your awesome plugin.
And Adobe will stop the security update of the npapi Linux flash in 2017 :m

**Comment by i-rinat** [comment]
> Why not add by default freshplayerplugin in the Firefox Linux builds?

Are you sure you're asking the right person? I'm not a Firefox (or Mozilla) developer.

**Comment by LifeIsStrange** [comment]
Yes I know of course sorry, Just a question you see no problem of make use of freshplayerplugin by default in Firefox ? 
Also please Where can I ask at mozilla ? Creating un bug at their bugzilla ?

**Comment by i-rinat** [comment]
> Also please Where can I ask at mozilla?

There is bugzilla, but there are already number of entries related to PPAPI support in Firefox. And freshplayerplugin is already mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=729481#c76

There are also mailing lists (or groups, can't say for sure what are they). [mozilla.dev.platform](https://groups.google.com/forum/#!forum/mozilla.dev.platform) and [mozilla.wishlist](https://groups.google.com/forum/#!forum/mozilla.wishlist) look relevant. All mailing lists catalog can be found on page https://lists.mozilla.org/listinfo, there can be more relevant lists.

**Comment by LifeIsStrange** [comment]
Thanks !!

**Comment by i-rinat** [comment]
> Just a question you see no problem of make use of freshplayerplugin by default in Firefox?

If you are talking about allowing to use freshplayerplugin bundled with other software, I have no objections. After all, freshplayerplugin is distributed under MIT license terms.

As for project state, it's more difficult question. There are still more than a dozen of open issues in tracker, which I can not solve. Development slowed down significantly, but there are still unimplemented parts.

I doubt it could be endorsed by Mozilla. Say they do so, and some bug appears. What should they do? Wait for me to fix it? Obviously distributing something together with Firefox means taking responsibility. What would they do that?

**Comment by LifeIsStrange** [comment]
Hum forgot they will never support ppapi as I understund on the bugzilla threads :/
"

**Comment by i-rinat** [comment]
> they will never support ppapi

They probably won't invest their time into PPAPI support themselves. Time and resources spent on PPAPI Flash are the time and resources which could be used to improve core browser parts. With Flash being phased out that looks like not a wise decision.

But if somebody does port on its own, so that it conforms with Firefox codebase rules; supports at least Windows, Mac OS X and Linux, disposition could change. Supporting a PPAPI implementation is worth benefits from sandboxed PPAPI Flash. In that case every interaction with outer world will be performed through Firefox well-tested code. That could help prevent many hardware-related issues, which are handled by Firefox itself, but not by Flash.

**Comment by madovsky** [comment]
well, people don't know that Firefox has been bought (silently) by Google to obviuosly kill it's main competitor and it's goal is to reduce as much as possible the percentage of users using Firefoxx.
and they did it well, in 3 years fireofx users fell down at around 20%.... I was at San Francisco 2 months ago and the office of Fireofx are in the same building of google. a bunch of guys there are (working?) for free(?) . anyhow, keep in mind that behind the scene it's always a question of power and money for the monopoly...

**Comment by LifeIsStrange** [comment]
You have true @madovsky BUT time is changing with THIS ! https://github.com/servo/servo
And this https://blog.mozilla.org/research/category/shumway/
This révolutions will be able for Firefox to largely win the technical point war. 
Ans Firefox already win the ethical war AND people begin to understund what is free software and how it is important (thanks to snowden)
Many school country programms will soon introduce the learn to the programmation and what is a free software ! The next génération will largely prefer free software over proprietary software. 
Also the growing of Linux and steamOS will increase the Firefox marketshare =) 
Don't be pessimist !

**Comment by madovsky** [comment]
@LifeIsStrange you are full of innocence, it recalls me the start of the open source community in 1999, full of dreams and hope... I'm not pessimist, I just provide some informations I had, so you can call it reality. 16 years after I can tell you that the Ying and Yiang exist for everything. whatever you hope behinde desperation is present. the trick is to balance both for the perfect equilibrium.
Don't expect to see  that it's good to teach everybody programming and work for free on a computer, it's the perfect slavery for those guys who won't need to pay anyone to profit from their code... that's the google, facebook, wikipedia  success...and today Microsoft too... tell people that programming is a game, and you will create an army of perfect slave who will never riot or ask anything but programming...
once you will be older, and see all your youth passed, get time to touch a tree, swim in a lake, be in love and connect to the nature so it will be too late....

**Comment by LifeIsStrange** [comment]
Okay you know the past and the present and so ? Me I see the future, the humanity is very young, see can and will change ! With many revolutions, immortality, artificial intelligence generalist, nanotechnologies, 3d printer, https://en.m.wikipedia.org/wiki/Basic_income 
, the begin of à capitalism more cooperative and less competitive, the World is changing. 
Google use the philosophy "The end justifies the means" Google don't make money for making money like others retarded companies, Google have a philosophy and it's improve the Humanity, improve the humanity with the IA and with the immortality (transhumanism). 
And if the World don't change, we can change the World, we need to change the World, I will create a Multinational of altruism which will compete against Google.  We are not spe

**Comment by madovsky** [comment]
Ho my.... well, ok I don't want to speculate or write tons of text since it's a freshplugin thread.
let's try to resume how this planet and our specie works since thousands years...
> Okay you know the past and the present and so ?
I don't know the past and the present, I just learn everyday since I born and die... learn how to not be slave, how to have real strong life values, like respect, cooperation, empathy, compassion and intelligence.

> Me I see the future
Projection is good, but the future is layers and layers of present... future never exist, the present only exist in a fraction of second, at least on our earth time..

>"The end justifies the means" Google don't make money 
1) I saw a lot of innocent programmers who wanted to grow like Mister Brin and Larry Wall 15 years ago, but never succeed, despite of their talents and creativity, why? :)
2) Google is a US corporation incorporated in Bahamas, with a capital of 300 billion dollars, 80% of shares made when they started to sell to the public zillions of shares in 2001. same story for Facebook. fresh money without to do anything.... or at least speculate and hire mass media to get involved in their game...
3) if Google don't make money, so how do they pay thousands of employees (wage of around $5000, dozen of data centers and so on?

> don't make money for making money like others retarded companies
what you think is retarded is only a business strategy. Microsoft are far away the most pragmatic. they just wait until their competitors die and buy the rest for a penny.. (aka sillicon valley 15 years ago until today). I encourage you to be less innocent and learn how the internet and computer business work before it's too late...
> Google have a philosophy and it's improve the Humanity, i
Are you copy and paste what they are saying or it's really coming from you???? :dancer: 
Google is a good search engine, the rest is gadgets. their philosophy is to monopoly the communication network and computer with their tools and OS, and diktat want kind of future they want to the humans.  
> improve the humanity with the IA and with the immortality (transhumanism)
an IA to travel through galaxies why not, but to replace human brains no thank you.
and imoortality for what? do you really think that give immortality to humans will be better?
look around you under and above your feet and start from the roots, why Google don't reveal that
the levitation technology allowing spacecraft to travel almost instantly thru the galaxies using stargates are a known technology since 80 years and much much older? why we need wheels and ex splosion engine to move, is Google has a solution for that? of course not, because they are part of the bad guys who want to control this planet (bildeberg, 300 richest entities of the planet who share more than 85% of its resources). If after that you think that Google is your god, well you must take (their medicine) to not see what's going on...

To change the human world, here is what we need:
1) use our own currency based on time (and why not gold) to avoid these crooks to print money for ever and nothing while you are working hours and hours to get this so little fake money to survive
2) Create RI (Real Intelligence) where people can meet and discuss about how to find a solution when a crook uses under law and power abuse to make money, power and threat other humans. a kind of instant constitution correction policy. only voted between people
3) constantly break any competition, and develop the new generations to not go in their trap again by a new kind of education. Learn to be more conscious, not to get a good wealthy job
4) solve the biggest problem of this planet, pollution. by revealing the 5000 patents confiscated by the CIA since 100 years like Tesla anti gravity, unlimited energy machine etc...
5) inject a maximum of human resources and machine on any kind of research to understand how the universe really works to have a chance one day to live on other planets...
