### ISSUE TITLE
Support of PPAPI for NPAPI VLC media player

### ISSUE THREAD

**Issue by proxy-m** [i-rinat/freshplayerplugin#317]
https://wiki.videolan.org/OPW_Summer_2014/#Port_VLC.27s_NPAPI_web_plugin_to_PPAPI
Rinat, maybe you help VLC project. They need something like your wrapper but in other side. Btw you can write VLC player plugin for PPAPI and then use your wrapper to make it work in Firefox. :-)

**Comment by i-rinat** [comment]
This project receiving less attention that I'd like it to receive, because I try to grasp too many projects at the same time. Rushing into another one doesn't look like a great idea. I also think there is no need of such plugins anymore, browsers are fine with video playback. At least, H.264 and VP9 are fine.

Then let's say, plugin is ported to PPAPI. Throwing it into a Chrome installation is a tricky procedure. It's quite easier with PNaCl, since that just works from a web page and doesn't require user to make any preparations. But video decoders in PNaCl will be significantly slower, since they are not allowed to have SIMD optimizations, like those that native browser decoders have. There are also a lot of limitations in networking code. (Or were, I didn't check that for a long time).

**Comment by proxy-m** [comment]
HTML5 + JavaScript does not support normal streaming protocols like RTSP, RTMP. I am forced to use HLS or MPEG-DASH. But I have source in RTSP. So firstly I convert RTSP to RTMP through ffmpeg. Then I take RTMP in nginx+rtmp-module. Then I take HLS from nginx+rtmp-module. But I want to take RTSP directly by VLC plugin. But Google Chrome does not support NPAPI anymore, so it's not cross-browser solution.

**Comment by madovsky** [comment]
let's do google go to hell...
