### ISSUE TITLE
midori crash,but i think freshplayerplugin also is related.

### ISSUE THREAD

**Issue by kuh3h3** [i-rinat/freshplayerplugin#319]
i reported this error to midori bug launchpad .
https://bugs.launchpad.net/midori/+bug/1563730

and attached full midori crash log.
https://launchpadlibrarian.net/250815531/fuul-midori-crash.log

**Comment by i-rinat** [comment]
The log file have backtrace in it. (There is a code in freshplayerplugin that calls `gdb` to collect backtrace if process crashes.) And that backtrace points somewhere into `libjavascriptcoregtk-1.0.so.0`.

Of course, there are memory corruption type of errors which are hideous, since place where error happened usually relatively far from the crash point. So it could be that freshplayerplugin causes the crash. Although it's highly unlikely, since Javascript engine allocates own memory block.

However there is no way to confirm or to refute.

**Comment by kuh3h3** [comment]
you are right. so i reported this error to webkit bugziila with more detailed 
[midori-webkitgtk-javascript-crash.txt](https://github.com/i-rinat/freshplayerplugin/files/200854/midori-webkitgtk-javascript-crash.txt)
log.

https://bugs.webkit.org/show_bug.cgi?id=156132

**Comment by i-rinat** [comment]
I don't think I can do anything about that crash, unless there is a stable way to reproduce it. There is no much sense in keeping this issue open.
