### ISSUE TITLE
Playback of DRM test is failing.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [i-rinat/freshplayerplugin#340]
Playback of Protected content under Flash is failing. I'd like to know if there is a  work around required such as installing ChromeOS Flash.

**Comment by i-rinat** [comment]
PepperFlash from desktop Chrome doesn't have DRM support, while PepperFlash from ChromeOS does.

If you have `libpepflashplayer.so` file, you can check for support by calling
```
strings -a libpepflashplayer.so | grep PPB_Flash_DRM
```
Version from ChromeOS have output like:
```
PPB_Flash_DRM;1.1
PPB_Flash_DRM;1.0
```
while for desktop one there is nothing.

**Comment by Zombie-Ryushu** [comment]
Adobe is now offering Pepper Flash as an independent download from Chromium.

**Comment by i-rinat** [comment]
> Is this Pepper Flash unable to do DRM?

Unable.

Test is the same, there should be string `PPB_Flash_DRM` inside a binary. Both i386 and x86-64 versions I tried have no such string inside.

You still can download ChromeOS recovery image directly from Google. It has PepperFlash inside.

**Comment by i-rinat** [comment]
This issue was about Flash plugin itself unable to do DRM-related computations. It's required to use version at from ChromeOS, since PepperFlash for desktop Chrome have no DRM-related code compiled in.

Additionally, there is another issue with DRM, #359. Reason is unknown. Probably, something Firefox-related, since drm test page works in Firefox 52 ESR on my machine.
