### ISSUE TITLE
Supporting the XDG specification

### ISSUE THREAD

**Issue by Sworddragon** [i-rinat/freshplayerplugin#343]
I'm using the freshplayerplugin 0.3.5 and noticing that things like the asset cache will be stored within ~/.config. For caches applications commonly follow the XDG specification to store them in the related path (commonly at default ~/.cache). Maybe the freshplayerplugin can do the same for caches too.

**Comment by i-rinat** [comment]
I thought about that, using `.cache` for cache. But there is no way to discern which files are cache and which are settings. They are just files for PPAPI. Since there is no reliable way to determine which part could be safely deleted, I store them all inside a subdirectory in `.config`. (So does Chrome).

**Comment by i-rinat** [comment]
Despite moving cache into `~/.cache` is generally a good idea, it cannot be implemented in this project.
