### ISSUE TITLE
Compiling at i686 machine

### ISSUE THREAD

**Issue by p00h** [i-rinat/freshplayerplugin#353]
Hello! I've got kinda situation over here:
```
#> uname -a
Linux ... 4.9.6-1-ARCH ... x86_64 GNU/Linux
#> git clone ... && mkdir build && cd build
#> cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 ../
#> make -j8
...
[ 39%] Building CXX object 3rdparty/angle/CMakeFiles/shader_translator.dir/src/compiler/translator/VersionGLSL.cpp.o
[ 39%] Linking CXX static library libshader_translator.a
[ 39%] Built target shader_translator
make: *** [Makefile:128: all] Error 2
```

Is it possible to cross compile the i686 version under x86_64 host machine? Or maybe Im doing something wrong. Let these things clear please! Any necessary data about my machine may be given immediately.

**Comment by i-rinat** [comment]
Hi.

Since you used `make -j8`, there were multiple compilation processes in parallel, and one of them failed. But there are no errors in lines you provided. Error was in the text before. Most likely there is `error:` text which you can search for in the whole output.

There are no strict x86-64 dependencies in the code, it should also compile in 32-bit mode. But since it uses Glib, it's tricky. Glib have architecture-dependent header files, so when you're compiling 32-bit code on a 64-bit machine, 64-bit version of `glibconfig.h` is included, which then fails on a static assertion.

I believe, there is a way to make all this work, by tweaking paths for `pkg-config`, for example. But the easiest way is to build in a 32-bit chroot.

**Comment by p00h** [comment]
Thank you very much! I'll do it that way.
