### ISSUE TITLE
Is v0.3.10 production-ready?

### ISSUE THREAD

**Issue by 86423355844265459587182778** [i-rinat/freshplayerplugin#379]
I noticed that there is a new version 0.3.10 in https://github.com/i-rinat/freshplayerplugin/releases, but [CMakeLists.txt](https://github.com/i-rinat/freshplayerplugin/blob/master/CMakeLists.txt) still declares version 0.3.9.

Is 0.3.10 production-ready, or is it just a placeholder?

**Comment by i-rinat** [comment]
I was trying to make changes that could brake everything, so I've added `v0.3.10` tag to mark the state where thing weren't broken yet. I haven't had a chance to make the changes yet though.

As moving existing tag is not a great idea, I've added https://github.com/i-rinat/freshplayerplugin/releases/tag/v0.3.11. It probably should be fine, as there were no big changes since 0.3.9.
