### ISSUE TITLE
Short proposal to add Windows (and other platforms) Support

### ISSUE THREAD

**Issue by mattatobin** [i-rinat/freshplayerplugin#64]
In the day and age where npapi flash is more and more unstable it occurs to some that this solution could be an answer for those on all platforms not just Linux.

If it can be demonstrated and proven the npapi wrapper for ppapi plugins can be done then we may have some leverage to convince Google to publish a standalone binary version of things like Pepper Flash for all platforms.

Additionally, multi-platform support could increase awareness, testing, and perhaps contributors to the project.

**Comment by i-rinat** [comment]
Hello again.

A lot of time has passed since the issue was opened, and I had enough time to think about it. Now I'm sure I won't be able to support other platforms, there's too much work involved.

Almost all code in the project is platform-dependent glue. Trying to support another couple of platforms will require at least twice more time. So since I already spent more than a year, that's another couple of years. Doesn't look feasible.
