### ISSUE TITLE
OS X support?

### ISSUE THREAD

**Issue by yegle** [i-rinat/freshplayerplugin#73]
Not sure if it worth the effort but I do want to have freshplayer in Firefox on OS X.

I choose not to install Flash Player in Firefox because of security concern. It will be great if freshplayer can be installed on OS X.

**Comment by i-rinat** [comment]
Hello again.

A lot of time has passed since the issue was opened, and I had enough time to think about it. Now I'm sure I won't be able to support other platforms, there's too much work involved.

Almost all code in the project is platform-dependent glue. Trying to support another couple of platforms will require at least twice more time. So since I already spent more than a year, that's another couple of years. Doesn't look feasible.

**Comment by wyatt8740** [comment]
oh, okay. thanks for following up anyway :)
