### ISSUE TITLE
Facebook Photo Albums

### ISSUE THREAD

**Issue by MALLER-LAGOON** [i-rinat/freshplayerplugin#83]
Hi, it's me again.

i've been notice that facebook photo uploads applies flashplayer to do the uploads. And when i try to create a new photoalbum, it really never popup. And this issue don't show any message to the console.

i don't know how can i get some info that can be usefull for this issue.

**Comment by MALLER-LAGOON** [comment]
this error is back, i don't know exactly from which commit, i will search for it.

every time that i try to create an photo album or simply add a pic into an album, the plugin crushes.

i did try with the last commit, and the error still there.

in console:

>NOT SANDBOXED
>[fresh 17702] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
>[fresh 17702] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
>[fresh] [warning] ppb_graphics3d_create, some of GLX_ARB_create_context, GLX_ARB_create_context_profile, GLX_EXT_create_context_es2_profile missing

>libva info: VA-API version 0.38.0
>libva info: va_getDriverName() returns 0
>libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/fglrx_drv_video.so
>libva info: Found init function __vaDriverInit_0_32
>libva info: va_openDriver() returns 0
>Failed to open VDPAU backend libvdpau_nvidia.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio

>(plugin-container:17770): GLib-GObject-WARNING **: cannot register existing type 'GdkWindow'

>(plugin-container:17770): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

>(plugin-container:17770): Gdk-CRITICAL **: gdk_window_ensure_native: assertion 'GDK_IS_WINDOW (window)' failed

>&#35;&#35;&#35;!!! [Parent][MessageChannel::Call] Error: Channel timeout: cannot send/recv
>&#35;&#35;&#35;!!! [Parent][MessageChannel::Call] Error: Channel timeout: cannot send/recv

**Comment by i-rinat** [comment]
> g_once_init_leave

This looks very suspicious. Similar error were from mixing GTK+ of versions 2 and 3 at the same time.
If it crashing, could you get a backtrace?

**Comment by MALLER-LAGOON** [comment]
how can i get a backtrace?

**Comment by i-rinat** [comment]
Here is how: [link](https://github.com/i-rinat/freshplayerplugin/blob/master/doc/debugging-guide.md#use-gdb-to-get-a-backtrace)

**Comment by MALLER-LAGOON** [comment]
Here is it.

https://www.dropbox.com/s/zy0w45hy3hlmkfz/core.register?dl=0

**Comment by i-rinat** [comment]
That's not exactly what I was talking about. During program execution various functions are called. They in turn call other functions and so on. When something unexpected happens, program gets terminated. But at that moment it has call history recorded in memory (it has to do that in order to know where to return from particular function). In debugging terms that's called backwards call trace, or backtrace for short.

To get that you load snapshot of program memory, so called core dump file, into gdb by running
```
$ gdb /usr/lib/firefox/plugin-container core
```
Then in gdb prompt you run `bt` or `backtrace`. Gdb parses stack for current thread and prints call history. Most programs today use multiple execution threads. To get backtraces of all threads, you call `thread apply all bt`.

**Comment by MALLER-LAGOON** [comment]
the thing is, i'm doing exactly what the guide says, but there is no core file anywhere.
i did look on desktop, on ~, even in the firefox folder, and nothing.

i don't really know what im doing wrong :/.

by the way, my firefox folder is located in ~/firefox, not in the /usr/lib/. it has something to do with the fact that i can't find the core file?

**Comment by MALLER-LAGOON** [comment]
i moved the firefox folder to the /usr/lib/firefox, and stills the same. i can't find any core file on it. :/

**Comment by MALLER-LAGOON** [comment]
i found the error!!

the problem indeed are the gtk libraries.
if i compile freshplayer with gtk+3, the mentioned problem occurs. but if i compile using gtk+2 libraries, the problem automatically disappears.

so apparently, there are some functional incompatibilities between gtk2 and 3 in the freshplayerplugin.

**Comment by i-rinat** [comment]
> there are some functional incompatibilities between gtk2 and 3 in the freshplayerplugin.

Firefox always [1] loads GTK+ 2 in plugin process. So when freshplayerplugin is linked with GTK+ 3, both versions get loaded.

If you have Firefox built with GTK+ 3 and want that version everywhere, including plugins, remove libmozgtk2.so, make symlink libmozgtk2.so pointing to libmozgtk.so, and build freshwrapper with GTK+ 3. That should work fine.


[1] In GTK+ 3 version Firefox uses a special trick which separates GTK+ versions, so in browser process it uses GTK+ 3, but `plugin-container` gets GTK+ 2. That is required for NPAPI Flash since it's linked with GTK+ 2.

**Comment by i-rinat** [comment]
> i can't find any core file on it

If plugin hangs for too long, which is 45 seconds by default, Firefox terminates plugin process. In that case no `core` file generated. I think that was the case.
